grinsfem/grins

src/physics/src/heat_transfer_stab_helper.C, src/physics/src/inc_navier_stokes_stab_helper.C
Cherry picked from #189. Thanks @vikramvgarg
=> Vikram's interior_rate fix

src/physics/src/heat_transfer_stab_helper.C, src/physics/src/inc_navier_stokes_stab_helper.C
This compiles for me now.
Also passes "make check" on my laptop, but I'd appreciate a double-check on that; I'm still not sure what bitrot crippled my Sysnet stack while I was away.
=> interior_rate only has the one version

test/antioch_evaluator_regression.C, test/antioch_kinetics_regression.C, test/input_files/stokes_poiseuille_flow_parsed_viscosity_parsed_conductivity_input.in, test/test_stokes_poiseuille_flow_parsed_viscosity_parsed_conductivity.C
Fixes for "make check" on Sysnet for me
=> Tolerance fixes

src/physics/src/velocity_penalty.C
This should hopefully fix the bug @nicholasmalaya encountered this afternoon.
=> VelocityPenalty2 distinct postprocessing names

src/physics/src/elastic_cable.C, src/physics/src/elastic_membrane.C, src/physics/src/multiphysics_sys.C
Fixes a couple of postprocessing bugs in the ElasticCable and ElasticMembrane Physics. Also fixed bug in the postprocessing if there were subdomain-restricted Physics enabled.
Will manually merge from 0.5.0-release into master.
=> Postprocessing fixes

src/physics/include/grins/reacting_low_mach_navier_stokes.h, src/physics/include/grins/reacting_low_mach_navier_stokes_base.h, src/physics/src/reacting_low_mach_navier_stokes.C, src/physics/src/reacting_low_mach_navier_stokes_base.C, src/physics/src/reacting_low_mach_navier_stokes_instantiate.C
Got rid of "helper" functions and moved some things to the base class in preparation for stabilization.
Merging to 0.5.0-release and will manually merge into master.
=> Condense Reacting low Mach Navier-Stokes

examples/suspended_cable/cable.in, src/physics/src/elastic_cable.C, src/physics/src/elastic_cable_constant_gravity.C, test/input_files/suspended_cable_test.in
Replaces #213 (history got a little munged). This is the last bit for the 0.5.0-release, other than clean up.
=> ElasticCable Jacobians

AUTHORS, CHANGES, examples/Makefile.am, src/Makefile.am, src/physics/src/elastic_cable.C, src/physics/src/physics_factory.C, test/input_files/suspended_cable_test.in, test/test_stokes_poiseuille_flow_parsed_viscosity_parsed_conductivity.C
Last set of changes for 0.5.0 release. Clean up for some warnings, fixes for `make distcheck`. Also updated CHANGES and authors.
@roystgnr, I think I rolled through the history OK, but you want to do a quick double check on the CHANGES/AUTHORS? Also, I listed you now as a lead developer in the AUTHORS file.
=> 0.5.0 Release Prep

src/apps/antioch_kinetic_rates.C
Makes more sense to take thermodynamic pressure from input
than the density.
=> Update input for antioch_kinetics_rates app

src/solver/src/grins.C
Wish I'd done this about 4 months ago (or earlier...). Should help with traceability.
=> Echo GRINS and libMesh hashses as well as command line.

m4/config_summary.m4, src/Makefile.am
This replaces #226 - same functionality but should be more forwards-compatible.
=> Use LIBMESH_LIBS with LIBMESH_LDFLAGS and display in config summary

src/physics/include/grins/physics.h, src/physics/src/multiphysics_sys.C, src/physics/src/physics.C
@nicholasmalaya needs a hook in #257 for init'ing the `ParsedFEMFunction`.
=> `Physics::auxiliary_init`

src/physics/include/grins/heat_conduction.h, src/physics/src/heat_conduction.C
This crap somehow snuck in. Removed.
=> Remove turd from HeatConduction

src/physics/include/grins/averaged_fan_adjoint_stab.h, src/physics/include/grins/averaged_turbine_adjoint_stab.h, src/physics/include/grins/velocity_drag_adjoint_stab.h, src/physics/include/grins/velocity_penalty_adjoint_stab.h, src/physics/src/averaged_fan_adjoint_stab.C, src/physics/src/averaged_turbine_adjoint_stab.C, src/physics/src/velocity_drag_adjoint_stab.C, src/physics/src/velocity_penalty_adjoint_stab.C
@pbauman caught this in the Boussinesq stabilization but it's also a
problem in the more obscure physics.
=> Use the Viscosity model in stabilization terms

src/Makefile.am, src/physics/include/grins/multiphysics_sys.h, src/physics/include/grins/physics.h, src/physics/src/multiphysics_sys.C, src/physics/src/physics.C, src/qoi/include/grins/composite_qoi.h, src/qoi/include/grins/qoi_base.h, src/qoi/src/composite_qoi.C, src/qoi/src/qoi_base.C, src/solver/include/grins/grins_solver.h, src/solver/include/grins/grins_steady_solver.h, src/solver/include/grins/parameter_manager.h, src/solver/include/grins/parameter_user.h, src/solver/include/grins/simulation.h, src/solver/include/grins/steady_mesh_adaptive_solver.h, src/solver/src/grins_steady_solver.C, src/solver/src/parameter_manager.C, src/solver/src/parameter_user.C, src/solver/src/simulation.C, src/solver/src/steady_mesh_adaptive_solver.C
This isn't yet complete (none of the Physics classes actually *register* parameters yet), but once that little detail is done we ought to be able to do forward and adjoint sensitivity solves.  The initial infrastructure is in place and ready for review; I'll continue adding to this branch until it's ready for merge.
=> Sensitivity solves

src/solver/include/grins/simulation.h, src/solver/include/grins/solver_context.h, src/solver/src/grins_steady_solver.C, src/solver/src/simulation.C, src/solver/src/steady_mesh_adaptive_solver.C, src/visualization/include/grins/steady_visualization.h, src/visualization/include/grins/unsteady_visualization.h, src/visualization/include/grins/visualization.h, src/visualization/src/steady_visualization.C, src/visualization/src/unsteady_visualization.C, src/visualization/src/visualization.C, test/input_files/parsed_qoi.in.in
Optional, and defaults to off, of course.
Right now this only works in cases where we're already doing a forward sensitivity solve; we'll probably want it to work in other cases as well later on.
=> Output solution sensitivities

src/solver/include/grins/simulation.h, src/solver/include/grins/solver_context.h, src/solver/src/grins_steady_solver.C, src/solver/src/simulation.C, src/solver/src/solver_context.C, src/solver/src/steady_mesh_adaptive_solver.C, src/visualization/include/grins/steady_visualization.h, src/visualization/include/grins/unsteady_visualization.h, src/visualization/include/grins/visualization.h, src/visualization/src/steady_visualization.C, src/visualization/src/unsteady_visualization.C, src/visualization/src/visualization.C
dR/dp should be useful for debugging.
=> Output residual sensitivities

src/solver/src/steady_mesh_adaptive_solver.C, src/visualization/include/grins/steady_visualization.h, src/visualization/include/grins/unsteady_visualization.h, src/visualization/include/grins/visualization.h, src/visualization/src/steady_visualization.C, src/visualization/src/unsteady_visualization.C, src/visualization/src/visualization.C
Added functions to output adjoint solutions. Have only tested the steady case using the cavity benchmark example. Seems to be doing the right thing.
=> Adjoint plotting

src/physics/src/reacting_low_mach_navier_stokes.C
Missed a term from divergence of velocity shape functions. Going to merge this quickly.
=> Missing axisymmetric term for reacting low Mach

src/physics/include/grins/physics_factory.h, src/physics/src/physics_factory.C
With new helper method in the same vein as the templated transport
helper functions.
I cherry picked this off my stabilization branch so that I could start upgrading Antioch interface from this point.
=> Replaced PhysicsFactory::add_reacting_low_mach

src/qoi/src/average_nusselt_number.C
I noticed this when working on the ParsedBoundaryQoI code.  libMesh
boundaries can have multiple ids, and we might specify those ids in
the qoi, and if we do then we probably don't want to double-count
contributions from the overlapping boundary region.
=> Fix Nusselt number for the overlapping bc_ids case

src/Makefile.am, src/qoi/include/grins/parsed_boundary_qoi.h, src/qoi/include/grins/qoi_names.h, src/qoi/src/parsed_boundary_qoi.C, src/qoi/src/qoi_factory.C, test/input_files/parsed_qoi.in.in
What it says on the box.  For problems without negligible diffusion, this will be more useful when combined with libMesh after https://github.com/libMesh/libmesh/pull/571 so that gradient terms are supported.
=> ParsedBoundaryQoI

README.md, examples/Makefile.am, examples/backward_facing_step/README, examples/backward_facing_step/run.sh.in
Feedback from Martin Luethi on things that should've been more clear.
=> Update README, Default Solver Options for Backward Facing Step Example

src/solver/include/grins/grins_solver.h, src/solver/src/grins_solver.C
Bugfix, history/formatting cleanup, and text nitpicking on top of #303 from @vikramvgarg
=> Add require_residual_reduction option

src/properties/include/grins/antioch_mixture_averaged_transport_mixture.h, src/properties/src/antioch_chemistry.C, src/properties/src/antioch_mixture.C, src/properties/src/antioch_mixture_averaged_transport_mixture.C
First step. Still limited to only ASCII parsing (vs. say ChemKin), but at least can specify non default data so makes this worthwhile merging sooner rather than later.
Don't have any tests here, but those will come with reacting-stab branch.
=> Antioch Input Generalization

test/axisym_reacting_low_mach_antioch_cea_constant_regression.sh.in
This works on up to 26 processors for me.  Nearly anything else I try
(including our previous go-to) breaks on 12 or less.
=> Hand-tweaked preconditioner choice, looser regression tolerance

configure.ac, src/Makefile.am, src/qoi/include/grins/average_nusselt_number.h, src/qoi/include/grins/parsed_boundary_qoi.h, src/qoi/include/grins/parsed_interior_qoi.h, src/qoi/include/grins/qoi_base.h, src/qoi/include/grins/qoi_names.h, src/qoi/include/grins/vorticity.h, src/qoi/include/grins/weighted_flux_qoi.h, src/qoi/src/average_nusselt_number.C, src/qoi/src/composite_qoi.C, src/qoi/src/parsed_boundary_qoi.C, src/qoi/src/parsed_interior_qoi.C, src/qoi/src/qoi_base.C, src/qoi/src/qoi_factory.C, src/qoi/src/vorticity.C, src/qoi/src/weighted_flux_qoi.C, src/solver/include/grins/simulation.h, src/solver/src/grins_unsteady_solver.C, test/Makefile.am, test/generic_solution_regression.C, test/input_files/parsed_qoi.in.in, test/input_files/poisson_weighted_flux_regression.in, test/poisson_weighted_flux_regression.sh.in
I want to add regression tests before merging, but the code should be in decent shape to examine.
=> Weighted flux qoi

src/physics/include/grins/averaged_fan_adjoint_stab.h, src/physics/include/grins/averaged_turbine_adjoint_stab.h, src/physics/include/grins/velocity_drag_adjoint_stab.h, src/physics/src/averaged_fan_adjoint_stab.C, src/physics/src/averaged_turbine_adjoint_stab.C, src/physics/src/velocity_drag_adjoint_stab.C
Founds these as part of the work in `input-materials-redo` branch. I'd like to merge this ASAP, and I've tested, but I'd still feel better if @nicholasmalaya hit this. @nicholasmalaya are you using these Physics? If so, could you run a case make sure this doesn't change anything for you?
=> More shadow fixes

src/solver/src/mesh_builder.C
This lets us run first order meshes with higher order elements.
@vikramvgarg will be testing shortly
=> Support Mesh/all_second_order after file read

src/Makefile.am, src/bc_handling/include/grins/generic_bc_handling.h, src/bc_handling/src/generic_bc_handling.C
Can't believe we didn't have this already. This is a small band-aid for the time being until I refactor the boundary condition handling, but will allow building, e.g.,  a `ConvectionDiffusion` physics.
=> GenericBCHandling

src/physics/include/grins/inc_navier_stokes_stab_helper.h, src/physics/src/inc_navier_stokes_stab_helper.C
Cherry-picked from my reacting stabilization branch.
=> Helper functions for axisymmetric tensor quantities

src/Makefile.am, src/physics/include/grins/reacting_low_mach_navier_stokes_macro.h, src/physics/src/reacting_low_mach_navier_stokes_instantiate.C
Macro to hide template heinousness.
=> Instantiation Macro for Reacting Low Mach Navier Stokes

src/Makefile.am, src/physics/include/grins/convection_diffusion.h, src/physics/src/convection_diffusion.C, src/physics/src/physics_factory.C, src/variables/include/grins/generic_fe_type_variable.h, src/variables/include/grins/generic_variable.h, src/variables/include/grins/single_fe_type_variable.h, src/variables/include/grins/single_variable.h, src/variables/src/single_fe_type_variable.C, src/variables/src/single_variable.C, test/Makefile.am, test/exact_soln/convection_diffusion_steady_1d.sh, test/input_files/convection_diffusion_steady_1d.in
Builds on #356, will rebase this once that's merged.
Plus an `exact_soln` test for the steady 1D case. 2-D+time-dependent case forthcoming in a separate PR (need to fix time-dependent Dirichlet BCs).
=> Add Convection Diffusion Physics

test/input_files/convection_diffusion_unsteady_2d.in
This fix-up commit somehow didn't make it into #359. Merging right away. Sorry for the trouble.
=> Fix convection_diffusion_unsteady_2d test

configure.ac, test/run_tests_parallel_loop.sh
=> Helper Script for Running Parallel Tests Repeatedly

examples/simple_fan/fan.in, examples/simple_prop/fan.in
These were supposed to be examples of rigid fans, not funky whirlpool motion.
=> Fan velocity at a point is proportional to r

src/Makefile.am, src/physics/include/grins/reacting_low_mach_navier_stokes_base.h, src/properties/include/grins/antioch_chemistry.h, src/properties/include/grins/antioch_mixture.h, src/properties/include/grins/cantera_mixture.h, src/properties/src/antioch_chemistry.C, src/properties/src/antioch_mixture.C, src/utilities/include/grins/parameter_antioch_reset.h, src/utilities/src/parameter_antioch_reset.C, test/input_files/reacting_low_mach_antioch_statmech_constant_regression.in
This fixes the conflicts from and obsoletes #291
=> Antioch parameter access (rebased)

src/properties/src/antioch_mixture_averaged_transport_evaluator.C
=> Squash warnings in Antioch interface

test/Makefile.am, test/exact_soln/poisson_periodic_2d_x.sh, test/exact_soln/poisson_periodic_2d_y.sh, test/exact_soln/poisson_periodic_3d_xy.sh, test/exact_soln/poisson_periodic_3d_xz.sh, test/exact_soln/poisson_periodic_3d_yz.sh, test/input_files/poisson_periodic_2d_x.in, test/input_files/poisson_periodic_2d_y.in, test/input_files/poisson_periodic_3d_xy.in, test/input_files/poisson_periodic_3d_xz.in, test/input_files/poisson_periodic_3d_yz.in
Realized we didn't have any formal test coverage of problems with periodic boundary conditions (the Rayleigh-Taylor example has it, but none of the tests). So, this PR drops in several 2D and 3D tests using Poisson equation to test periodic boundary conditions. No AMR at this point, mainly interested in having input specification tested. Tested all on 1 and 4 processors.
As a side note, really need to move all the other tests to this form (run main problem through GRINS, then have an app checkout the output). It was *super* easy to add these tests.
=> Periodic Boundary Condition exact_soln Tests

src/qoi/src/rayfire_mesh.C
Compilation fix with GCC 5.3.0 for RayfireMesh. Whitespace fixes.
=> RayfireMesh Fix

src/boundary_conditions/src/default_bc_builder.C
This fixes errors where we were assuming that BoundaryInfo was
returning global info but it was actually returning only local info.
Apologies to @pbauman for the poor API documentation there, which
should be fixed by https://github.com/libMesh/libmesh/pull/1032
This doesn't get "make check" passing for me yet, but it fixes 90+% of the failures I was seeing initially.
=> Handle boundary_info on distributed meshes

src/physics/src/reacting_low_mach_navier_stokes_spgsm_stab.C
But at some point our Makefile updated it for me.
=> Somehow boilerplate missed this file earlier

src/qoi/src/rayfire_mesh.C, test/unit/rayfireAMR_test.C
Upon refinement of rayfire elements, if the rayfire enters a parent element very near the boundary between 2 children, the starting child is not properly calculated.
A CPPUnit test was added to verify that the issue is resolved.
=> Bugfix for RayfireMesh refinement

src/boundary_conditions/src/constant_function_dirichlet_bc_factory.C, src/boundary_conditions/src/parsed_function_dirichlet_bc_factory.C, src/boundary_conditions/src/parsed_function_dirichlet_old_style_bc_factory.C, src/boundary_conditions/src/pressure_pinning.C, src/physics/src/multiphysics_sys.C, src/qoi/src/composite_qoi.C, src/qoi/src/parsed_boundary_qoi.C, src/qoi/src/parsed_interior_qoi.C, src/solver/include/grins/grins_unsteady_solver.h, src/solver/src/grins_solver.C, src/solver/src/grins_unsteady_solver.C, src/solver/src/simulation.C, src/solver/src/steady_mesh_adaptive_solver.C, src/strategies/include/grins/adjoint_error_estimator_factories.h
=> libmesh_cast_<ref/ptr> -> cast_<ref/ptr>

test/regression/elastic_mooney_rivlin_membrane_cantilever_unsteady_rayleigh_damping.sh
I get ~3e-10 errors here, which seem tolerable.
=> Loosen 1e-10 tolerance

src/Makefile.am, src/physics/include/grins/physics_naming.h, src/physics/include/grins/variable_pinning.h, src/physics/src/physics_factory_basic.C, src/physics/src/variable_pinning.C, src/solver/src/grins_unsteady_solver.C
I didn't end up using this, but it works as advertised and others might find it useful.
=> VariablePinning physics

src/qoi/src/hitran.C
Small change to ensure the specified temperature range includes the HITRAN reference temperature 296K.
=> HITRAN temperature range checks

src/boundary_conditions/src/pressure_pinning.C, src/physics/include/grins/inc_navier_stokes_stab_helper.h, src/physics/src/inc_navier_stokes_base.C, src/physics/src/inc_navier_stokes_stab_helper.C, src/physics/src/low_mach_navier_stokes_base.C, src/physics/src/reacting_low_mach_navier_stokes.C, src/physics/src/reacting_low_mach_navier_stokes_abstract.C, src/physics/src/reacting_low_mach_navier_stokes_spgsm_stab.C, src/physics/src/reacting_low_mach_navier_stokes_stab_base.C, src/physics/src/stab_helper.C
Not yet sure that this is complete, and I'll probably end up saying "forget it, let's just make a strip of quads" before it is, but I think this is at least a good start.
=> 1-D fixes for Reacting Low Mach Navier-Stokes

src/physics/include/grins/physics_factory_reacting_flows.h, src/physics/src/physics_factory_reacting_flows.C
We should probably get an antioch-free build into the GRINS Civet recipes.
=> Fix builds with Antioch disabled

src/common/include/grins/factory_abstract.h
This fixes the issue in libMesh/libmesh#1515 for me.
=> Include libmesh_common.h for libmesh_error_msg().

src/boundary_conditions/include/grins/catalycity_factory_abstract.h, src/boundary_conditions/include/grins/neumann_bc_factory_abstract.h, src/physics/include/grins/physics_factory_base.h, src/solver/include/grins/solver_factory_abstract.h, src/strategies/include/grins/error_estimator_factory_base.h, src/variables/include/grins/variable_factory.h
This gets GRINS compiling for me with clang, thanks @roystgnr for compiler diagnostic interpretation.
Fixes #510.
=> Fix specialization-after-instantiation errors.

test/amr/convection_diffusion_unsteady_2d.sh, test/amr/convection_diffusion_unsteady_2d_petsc_diff.sh
Some files weren't getting cleaned up and it was breaking distcheck.
=> Remove testing turds

test/unit/input_files/variables_species_antioch.in, test/unit/variables.C
This should've been part of #550 but was overlooked.
=> Add missing test

src/physics/src/physics_factory_reacting_flows.C, src/properties/src/antioch_mixture_builder_base.C, src/properties/src/materials_parsing.C, test/test_data/CO2_N2.xml, test/unit/input_files/spectroscopic_base.in
These issues are extremely minor and inconsequential, but they are annoying and clogged up some log files. Particularly getting rid of the deprecated warnings from the spectroscopic tests was a big help.
=> Fix Annoyances

src/solver/include/grins/mesh_builder.h, src/solver/src/mesh_builder.C
And cleaned up a few other code smells.
=> Remove deprecated input options from MeshBuilder

src/physics/src/scalar_ode.C, src/qoi/src/parsed_qoi_base.C, src/qoi/src/qoi_factory.C, test/unit/integrated_function_test.C
=> Use std::make_unique, not libmesh_make_unique
