src/solver/include/grins/simulation.h, src/solver/include/grins/solver_context.h, src/solver/src/grins_unsteady_solver.C, src/solver/src/simulation.C, src/solver/src/solver_context.C, test/input_files/dirichlet_fem.in
This is a feature @nicholasmalaya may find useful - we output the accumulating PerfLog data every N timesteps, not just at the end of a simulation, so there's less of a wait time before being able to examine performance changes.
One oddity: due to the way the libMesh PerfLog works, we get the machine info with the first print, and not with any subsequent prints.  I think this is the best way to do things, but it looks weird and I can move the machine info back to the final PerfLog if that's preferred.
=> Print perflog mid-simulation if requested

examples/laminar_flame/bunsen.in, src/visualization/src/postprocessed_quantities.C
@roystgnr rightly pointed out that I should've had a warning scream at you if you still use vis-options/output_vars following #167. This adds such a warning. Also throw libmesh_error() for now.
Set to merge to 0.5.0-release. Will manually merge to master once the PR merges.
=> Warning and error when using outdated vis-options/output_vars

src/physics/src/physics_factory.C
std::shared_ptr can be constructed from NULL, but the
boost::shared_ptr version that @nicholasmalaya is using apparently
cannot.  Both should have working default constructors, though.
=> Possible bugfix for a build failure on lonestar

src/physics/include/grins/physics.h
Otherwise it's too easy to break Physics classes (as the current
PhysicsFactory code does) by passing in temporaries to their
constructors.
=> Copy, don't reference, physics_name strings

src/physics/include/grins/multiphysics_sys.h, src/physics/src/multiphysics_sys.C, src/visualization/src/postprocessed_quantities.C
Basically in conjunction with libMesh/libmesh#467. With that plus this PR, master `make check` runs cleanly.
=> Guard against get_elem() calls for SCALAR variables

doxygen/grins.dox.in
Fixes Doxygen input file to actually build documentation for all the classes. This required 1. updating the INPUT variable (just tell it look in src and it will find everything) and 2. actually including Antioch and Cantera. We could've accomplished 2 by cluing Doxygen into grins_config.h in the build directory where then it would only include Antioch, for example, if it was actually present in the build. Using the PREDEFINED variable, we can tell Doxygen to just define those preprocessing parameters so that their documentation is always built. I prefer this so that we just always have the documentation for everything built all the time.
Set to merge to 0.5.0-release, will manually merge to master after this PR is merged.
Will leave this up for comments tonight and then merge tomorrow if …
=> Doxygen update

src/properties/include/grins/antioch_chemistry.h, src/properties/include/grins/antioch_constant_transport_evaluator.h, src/properties/include/grins/antioch_constant_transport_mixture.h, src/properties/include/grins/antioch_evaluator.h, src/properties/include/grins/antioch_kinetics.h, src/properties/include/grins/antioch_mixture.h, src/properties/include/grins/antioch_wilke_transport_evaluator.h, src/properties/include/grins/antioch_wilke_transport_mixture.h, src/properties/include/grins/cantera_evaluator.h, src/properties/include/grins/cantera_mixture.h, src/properties/include/grins/cantera_thermo.h, src/properties/include/grins/cantera_transport.h
Main thing was to mention that documentation is always built regardless of whether Antioch/Cantera was detected during the build.
=> Antioch/Cantera Doc Updates

CHANGES, README.md, configure.ac
Also, I think I accidentally had overwritten the libMesh version requirement. It's back to 1.0.0 now. Also updated README.
=> Bump Version to 0.6.0

src/physics/src/inc_navier_stokes_base.C
Contrary to 08e99bc49c27c8fdd6ab86336aa310fa05d39774, this really
should be physics_name because Stokes is subclassing this and
we should be able to parse Stokes section. Uncovered this as part of
turning on UFO detection.
I actually think that the variable classes could actually be treated
as "mixins" and we use multiple inheritance in the root physics classes
with these variable classes. Another day...
Make check is passing for me with this change.
=> Pass physics_name to flow_vars in IncompressibleNavierStokesBase

CHANGES, src/physics/include/grins/grins_physics_names.h, src/physics/src/physics_factory.C, src/physics/src/velocity_penalty.C, src/physics/src/velocity_penalty_base.C
The pull request adds the option for a third velocity penalty definition. This is necessary in order to create walls, where the all three velocity components are constrained to zero. 
This largely parrots @roystgnr work from #160.
=> VelocityPenalty3 to constrain all components of velocity

CHANGES, src/solver/include/grins/grins_solver.h, src/solver/src/grins_solver.C
This pull request adds a new input line to the parser, permitting the user to dictate that the routine either throws an exception or continues when the non-linear solver does not converge. In particular, in the latest GRINS, the default behaviour is to continue on the merry way, such as,
<pre>
Nonlinear solver reached maximum step 10, latest evaluated residual
0.291611                                                    
Continuing...           
</pre>
Now, the default behaviour is to throw an exception, unless the flag, 'continue_after_max_iterations' is set to true. I would prefer this to be the case, as I want to know this is happening and explicitly give permission, but this is admittedly a change from the previous GRINS settings, and I'm happy to switch it back to 'true' (and …
=> Continue after max iterations

src/solver/include/grins/solver_context.h, src/solver/src/simulation.C, src/solver/src/steady_mesh_adaptive_solver.C
Only print the QoI if the user requests it in the adaptivity solver.
Really, we need to do additional checking on if the user has actually set a QoI to handle cases were they set print_qoi = 'true', but don't actually have a QoI; will open a ticket for that. For now, this is a quick fix.
=> Adaptivity printqoi fix

src/physics/src/heat_transfer.C, src/physics/src/inc_navier_stokes.C, src/physics/src/low_mach_navier_stokes.C, src/physics/src/reacting_low_mach_navier_stokes.C, src/physics/src/velocity_penalty.C, src/visualization/src/postprocessed_quantities.C
Each Physics class is responsible for its own postprocessing variables (following #167) by registering with PostprocessedQuantities and getting an `unsigned int` back so that PostprocessedQuantities can later request the evaluation of that quantity without using string comparisons. There were 2 issues here and I can't believe they didn't bite us earlier in much worse ways.
1. Many of the index variables weren't initialized in the Physics classes so we were getting uncertain behavior. This is why things changed based on the order requested, number of processors, etc.
2. PostprocessedQuantities was counting from zero so if the default for the `unsigned int`s was zero, and the 0 variable was requested, you would've gotten the first quantity that was indexed at zero, whether you requested it …
=> Fix Postprocessing Index Heisenbug

src/solver/src/grins.C
Otherwise we aren't ready for any libmesh_error() calls from the GetPot initialization.
That was originally an infinite loop prompting https://github.com/libMesh/libmesh/pull/503 but even with that fixed we can't query the libMesh command line for gdb version until after LibMeshInit construction.
=> Initialize libMesh earlier

src/solver/include/grins/simulation.h, src/solver/src/simulation.C
Created several helper functions to condense code in the constructor. Created a new constructor that additionally takes a GetPot& for the command line parsing. Deprecated the previous constructor.
This is in preparation for adding command line flag to warning instead of error on UFO detection. I went this route because it looked unsafe to have a single GetPot object parse both the input file and command line. Also didn't like the idea of shoving it in the SimulationBuilder. And it's probably a good idea to have access to the command line anyway.
=> Simulation constructor refactor

configure.ac, src/solver/include/grins/simulation.h, src/solver/src/grins.C, src/solver/src/simulation.C, test/Makefile.am, test/error_ufo_unit.sh.in, test/input_files/ufo_unit.in, test/ufo_unit.C, test/warn_only_ufo_unit.sh.in
Following some complaints about the lack of this option, this PR enables only warnings, instead of errors, if UFOs are detection. Namely, add the option "--warn-only-unused-var" on the command line sometime after the input file (the input file must be the first option listed after the grins executable (we should probably add some flexibility here)) and any detected UFOs will only illicit a warning and the list of UFOs instead of an error. I've also added unit tests for both the warning and the error versions.
This builds off of #248 (for command line access in `Simulation`).
=> Enable only warnings for UFO detection with command line option

test/input_files/vorticity_qoi.in.in, test/test_vorticity_qoi.C, test/test_vorticity_qoi.sh.in
Discovered this while adding the Parsed QoI run case.  It turns out that all this time, make check has been verifying that the Vorticity QoI *runs* but hasn't actually been calling the test harness that verifies the output is correct.
We should probably generalize that test harness to use for other QoI cases too, but for now we can at least turn it on for Vorticity.
=> Actually test vorticity qoi

src/solver/src/simulation.C
We just got a segfault (opt) or a cast failure (devel) before.
Tested and working.
=> Catch "print_qoi with no QoIs" error earlier

test/input_files/sa_2d_turbulent_channel_regression.in, test/test_turbulent_channel.C
This gets "make check" working again with --enable-parmesh and with different processor counts.
=> SA test fixes

src/physics/include/grins/var_typedefs.h, src/physics/src/primitive_flow_variables.C, src/physics/src/primitive_temp_variables.C, src/physics/src/solid_mechanics_variables.C, src/physics/src/turbulence_variables.C
In some cases we initializing variable indices, in some cases we weren't. This is problematic for development cases like forgetting to initialize variables with libMesh since the `VariableIndex` is an `unsigned int` and can often default to 0. This PR defines `GRINS::invalid_var_index` and, for the cases where we've wrapped up the variable indices, use this to initialize the var indices. Note I'm using `std::numeric_limits<unsigned int>::max()` as the invalid value since we can't use negative values. If there's a better suggestion, I welcome it.
=> More consistent var index initialization

CHANGES, src/bc_handling/src/spalart_allmaras_bc_handling.C, src/physics/src/heat_conduction.C, test/Makefile.am
Builds off of #284.
Removed a few more unused variable warnings. Now the only warnings that are emitted should be from new Antioch and Cantera. `make distcheck` passes for me. Updated CHANGES.
Chime in now if there's anything else you want to try and squeeze in. Otherwise I'll tag and release tonight.
Closes #283.
=> 0.6.0 prep

src/solver/src/grins.C
Otherwise a failure in GetPot initialization just goes straight to a stack trace without outputting anything else useful.
=> Print header information earlier

src/physics/include/grins/antioch_instantiation_macro.h
This should've been added as part of commit
bf2889f5d27d15ed72f5bdd6ef6526f08e194266 but was mistakenly missing.
Continuous integration with GitHub would be nice...
Going to merge ASAP as master will currently not compile when using Antioch.
=> Add missing instantiation macro

src/physics/include/grins/heat_transfer_stab_base.h, src/physics/src/heat_transfer_stab_base.C
Came across this in the `input-materials-redo` branch. The member in question is in `HeatTransferBase`. Do we disable `-Wshadow`? Supposedly gcc 4.8 is better with this.
I tested this locally so I'm going to go ahead and merge right away.
=> Remove redundant protected member from HeatTransferStabBase

src/Makefile.am, src/properties/include/grins/parsed_conductivity.h, src/properties/include/grins/parsed_property_base.h, src/properties/include/grins/parsed_viscosity.h, src/properties/src/parsed_conductivity.C, src/properties/src/parsed_property_base.C, src/properties/src/parsed_viscosity.C
Saw this in my `input-materials-redo` branch and couldn't resist. Collected common code from `ParsedConductivity` and `ParsedViscosity` into a base class.
=> Parsed Property Refactor

src/qoi/src/parsed_boundary_qoi.C
This should fix some nasty ParsedBoundaryQoI bugs; previously adjoint and sensitivity solves wouldn't work and even QoI evaluation only worked correctly if your parsed function was zero on non-specified boundaries.
@vikramvgarg has some more tests to run before merge.
=> Parsed bcid fix

src/physics/include/grins/averaged_fan_base.h, src/physics/include/grins/averaged_turbine_base.h, src/physics/include/grins/parsed_velocity_source_base.h, src/physics/include/grins/scalar_ode.h, src/physics/include/grins/velocity_drag_base.h, src/physics/include/grins/velocity_penalty_base.h, src/physics/src/averaged_fan_base.C, src/physics/src/averaged_turbine.C, src/physics/src/averaged_turbine_base.C, src/physics/src/parsed_source_term.C, src/physics/src/parsed_velocity_source_base.C, src/physics/src/scalar_ode.C, src/physics/src/velocity_drag_base.C, src/physics/src/velocity_penalty.C, src/physics/src/velocity_penalty_base.C, src/properties/include/grins/parsed_property_base.h, src/properties/src/parsed_conductivity.C, src/properties/src/parsed_viscosity.C, src/qoi/src/average_nusselt_number.C, src/qoi/src/parsed_boundary_qoi.C, src/qoi/src/parsed_interior_qoi.C, src/solver/include/grins/parameter_user.h, src/solver/src/parameter_user.C, test/input_files/parsed_qoi.in.in
This requires https://github.com/libMesh/libmesh/pull/667
We can now calculate sensitivities WRT inline variables in any parsed functions other than those imposed through boundary conditions.
@nicholasmalaya and @vikramvgarg might find this useful
This incorporates #314; we'll merge those two commits and pull that PR separately first and then rebase this off that; I just wanted to put the code out there for perusal now that it's passing tests with correct results.
=> Parsed function variable sensitivities

src/solver/src/simulation.C
So we shouldn't need to specify do_adjoint_solve manually in the input file before outputting z.
=> Adjoint sensitivities include an adjoint solve

src/physics/include/grins/multiphysics_sys.h, src/physics/src/multiphysics_sys.C, test/input_files/low_mach_cavity_benchmark_regression_input.in
Requires https://github.com/libMesh/libmesh/pull/669 to compile.
Not currently exercised in regression tests, but works as expected on
my own input files
=> Add numerical_jacobian_h_variables/values options

src/qoi/include/grins/weighted_flux_qoi.h, src/qoi/src/weighted_flux_qoi.C
To make the syntax intuitive there must be one variable and one bc id
per weight, so now the syntax is more repetitive.
I haven't tested this much; @vikramvgarg make sure it doesn't regress your existing drag calculations before you try the angle-of-attack stuff.
=> Allow WeightedFlux to use per-variable weights

src/physics/include/grins/velocity_penalty_base.h, src/physics/src/velocity_penalty.C, src/physics/src/velocity_penalty_adjoint_stab.C, src/physics/src/velocity_penalty_base.C
This may be necessary for some of @nicholasmalaya 's experiments.
This passes our VelocityPenalty regression tests but probably shouldn't be merged until Nick has time to play with it.
=> Use ParsedFEM- not Parsed-Func in VelocityPenalty

src/error_estimation/src/error_estimation_factory.C, src/solver/include/grins/mesh_adaptive_solver_base.h, src/solver/include/grins/steady_mesh_adaptive_solver.h, src/solver/src/mesh_adaptive_solver_base.C, src/solver/src/simulation.C, src/solver/src/steady_mesh_adaptive_solver.C
Changes to allow user to request an Adjoint Refinement Error Estimate for a QoI. 
Passes make check and tested with parsed laplace regression. Core capability verified earlier in libMesh.
=> Adjoint refinement options input

src/physics/src/elastic_cable.C, src/physics/src/elastic_membrane.C, src/qoi/src/vorticity.C, src/solver/src/mesh_builder.C, src/solver/src/parameter_user.C, src/utilities/include/grins/distance_function.h
cppclean was run on the libMesh tree and we needed to add a few
missing headers as a result.
=> Fixes for libMesh/libmesh#701

src/Makefile.am, src/bc_handling/include/grins/axisym_heat_transfer_bc_handling.h, src/bc_handling/include/grins/low_mach_navier_stokes_bc_handling.h, src/bc_handling/include/grins/reacting_low_mach_navier_stokes_bc_handling.h, src/bc_handling/src/axisym_heat_transfer_bc_handling.C, src/bc_handling/src/low_mach_navier_stokes_bc_handling.C, src/bc_handling/src/reacting_low_mach_navier_stokes_bc_handling.C, src/physics/include/grins/axisym_boussinesq_buoyancy.h, src/physics/include/grins/axisym_heat_transfer.h, src/physics/include/grins/low_mach_navier_stokes_base.h, src/physics/include/grins/reacting_low_mach_navier_stokes_base.h, src/physics/include/grins/species_mass_fracs_fe_variables.h, src/physics/include/grins/species_mass_fracs_variables.h, src/physics/include/grins/thermo_pressure_fe_variable.h, src/physics/include/grins/thermo_pressure_variable.h, src/physics/src/axisym_boussinesq_buoyancy.C, src/physics/src/axisym_heat_transfer.C, src/physics/src/low_mach_navier_stokes.C, src/physics/src/low_mach_navier_stokes_base.C, src/physics/src/low_mach_navier_stokes_braack_stab.C, src/physics/src/low_mach_navier_stokes_spgsm_stab.C, src/physics/src/low_mach_navier_stokes_stab_base.C, src/physics/src/low_mach_navier_stokes_vms_stab.C, src/physics/src/reacting_low_mach_navier_stokes.C, src/physics/src/reacting_low_mach_navier_stokes_base.C, src/physics/src/species_mass_fracs_fe_variables.C, src/physics/src/species_mass_fracs_variables.C, src/physics/src/thermo_pressure_fe_variable.C, src/physics/src/thermo_pressure_variable.C, test/input_files/axi_thermally_driven_flow.in
This effectively completes what was started in #73, namely encapsulating the variable name parsing and variable initialization with the `libMesh::System` into standalone classes. Then, updating `Physics` classes to only use these objects to handle variables. This is opposed to the scattered mess that was there before. The design follows as before: `*Variable` classes for basic handling of variable name and index (primarily used in `BCHandling` classes) and `*FEVariable` subclasses for the finite element space (used in the `Physics` classes).
The first set of commits updates the `Physics` and `BCHandling` classes that could've used already existing `(FE)Variable` classes. Then, I added thermodynamic pressure and species mass fraction versions of the `(FE)Variable` classes and then used …
=> Consolidate Variable Initialization/Usage

src/common/include/grins/common.h
And that's OK because we were *lying*. The source was built at __DATE__
and __TIME__ since this is GRINS and not libMesh.
=> __LIBMESH_<DATE,TIME>__ are no longer defined

src/properties/src/materials_parsing.C, src/solver/src/simulation.C, test/input_files/backward_facing_step.in.in
It makes sense to want to dump all the material properties you have for a given material in the input file. So, we need to turn off the error for unused variables for any variables in the `[Materials]` section.
I also double checked that if we had misspellings in property names, using the new input format for material properties, we'd still get an error (some of the older properties had some really insane default behavior before if there was no variable specified). Turned out `Density` slipped through the cracks there, i.e. you could be using the new option, misspelled the input parameter and not gotten an error. Fixed that as well. All the other properties checked out.
=> Unused Material Properties are Not GetPot UFOs

examples/backward_facing_step/backward_facing_step.in, examples/coupled_stokes_navierstokes/stokes_ns.in
Instead of outdated `ParabolicProfile`
=> Update Examples to use parsed_dirichlet Boundary Condition

test/test_axi_ns_con_cyl_flow.sh.in
The change was in the default behavior on the shift type for PC ilu.
See this thread: http://lists.mcs.anl.gov/pipermail/petsc-users/2016-January/028210.html
@dknez I have a vague memory of you mentioning some failures that happened with PETSc >= 3.6.0, but I can't find the thread now. I'd bet this was the culprit. If I'm misremembering, sorry for the noise.
Merging right away.
=> Fix test that was failing with PETSc >= 3.6.x

src/solver/include/grins/grins_solver.h, src/solver/include/grins/grins_unsteady_solver.h, src/solver/include/grins/mesh_adaptive_solver_base.h, src/solver/include/grins/steady_mesh_adaptive_solver.h, src/solver/src/grins_solver.C, src/solver/src/grins_steady_solver.C, src/solver/src/grins_unsteady_solver.C, src/solver/src/mesh_adaptive_solver_base.C, src/solver/src/steady_mesh_adaptive_solver.C
Internal restructuring of `Solvers`. Mostly creating helper functions to promote future reuse. Also made `MeshAdaptiveSolverBase` standalone from `Solver`. 
In doing the restructuring, I also noted that we're not calling `reinit_constraints` for time-dependence in the boundary conditions, only nonlinear dependence. Will fix that in a subsequent PR.
=> Solver Restructuring

src/Makefile.am, src/physics/include/grins/physics_factory.h, src/physics/include/grins/physics_naming.h, src/physics/src/physics_factory.C, src/physics/src/physics_naming.C, test/input_files/convection_cell_regression.in, test/input_files/couette_flow_input_2d_x.in, test/input_files/elastic_mooney_rivlin_circle_hookean_stiffeners_regression.in.in
This PR enables using `:` in the input physics name and putting whatever suffix you want. This will allow us to use the same physics in different ways. For example:
<pre>
[Physics]
enabled_physics = 'ElasticMembrane ElasticCable:Stringer ElasticCable:RingCable]
[./ElasticMembrane]
[../ElasticCable:Stringer]
enabled_subdomains = '0'
material = 'Kevlar'
[../ElasticCable:RingCable]
enabled_subdomains = '1'
material = 'ThickKevlar'
[]
</pre>
The way I did this is by stashing the suffix in `PhysicsNaming`. The returned physics name will always have a suffix appended to it; the suffix is empty until the user sets it. For each physics we build, we first extract the suffix, set it, then it will propagate all the way through during the build phase of the physics, e.g. for stabilization classes …
=> Multiply Enabled Physics From Input

src/apps/antioch_transport_values.C, src/apps/cantera_kinetic_rates.C, src/physics/src/reacting_low_mach_navier_stokes.C, src/properties/include/grins/antioch_constant_transport_evaluator.h, src/properties/include/grins/antioch_evaluator.h, src/properties/include/grins/antioch_kinetics.h, src/properties/include/grins/antioch_mixture.h, src/properties/include/grins/antioch_mixture_averaged_transport_evaluator.h, src/properties/include/grins/cantera_evaluator.h, src/properties/include/grins/cantera_kinetics.h, src/properties/include/grins/cantera_thermo.h, src/properties/include/grins/cantera_transport.h, src/properties/src/antioch_constant_transport_evaluator.C, src/properties/src/antioch_evaluator.C, src/properties/src/antioch_kinetics.C, src/properties/src/antioch_mixture.C, src/properties/src/antioch_mixture_averaged_transport_evaluator.C, src/properties/src/cantera_evaluator.C, src/properties/src/cantera_kinetics.C, src/properties/src/cantera_thermo.C, src/properties/src/cantera_transport.C, test/interface/antioch_evaluator_regression.C, test/interface/antioch_mixture_averaged_transport_evaluator_regression.C, test/interface/cantera_chem_thermo_test.C, test/interface/cantera_evaluator_regression.C, test/interface/cantera_transport_regression.C
Completely reworked the Mixture/Evaluator interface for Antioch and Cantera that's mainly by the reacting low Mach `Physics`. Got rid of the (stupid) `CachedValues` interface there. I'm still not very happy with this, but it's a step in a better direction.
=> Refactor Antioch/Cantera Interface

CHANGES, examples/simple_fan/fan.in, src/physics/include/grins/averaged_fan.h, src/physics/src/averaged_fan.C
This pull adds registration as well as output for the base velocity in the averaged fan physics. It also adds a demonstration of this capability to the examples for the averaged fan example. 
Implementation was simple and was heavily based off of a similar existing capability in velocity penalty. Appears to be working for me. Make check is passing locally on my laptop as well as in an ICES environment.
=> support output_vars = 'base_velocity' to averaged_fan

src/properties/include/grins/antioch_evaluator.h
Before, we were checking just T. However, in both the cache and
the argument coming in, T is a reference. So, if T changed upstream,
then the expression evals to true even though we need to rebuild
the TempCache. So, we'll check the next cheapest thing, which is T^2.
This didn't bite us in the PDE solves because we actually had different
addresses for T when constructing this, but it would produce incorrect
results from the thermo apps. Picked up on this in a separate branch
where I'm adding CppUnit-based tests of the thermochemistry interfaces.
This is really a symptom of a bad design decision, I think. What I think we should do is make a "compute all the things for reacting low Mach Navier-Stokes" method and remove this function entirely. Then, if the user wants to use the single …
=> Check T^2 in AntiochEvaluator::check_and_reset_temp_cache

configure.ac, doxygen/grins.dox.in, m4/common/cppunit.m4, m4/config_summary.m4, test/Makefile.am, test/common/grins_test_paths.h.in, test/common/testing_utils.h, test/interface/air_nasa_poly_base.h, test/interface/antioch_test_base.h, test/interface/antioch_thermo.C, test/interface/cantera_test_base.h, test/interface/cantera_thermo.C, test/interface/interface_cppunit_test.C, test/interface/nasa_poly_test_base.h, test/interface/thermochem_test_common.h
The first bit of this PR adds a check for CppUnit and adds paths accordingly to the test/Makefile.am. The only catch here is: 1. If your system is GCC 4.x based and you're using GCC 5.y, you need to build your own CppUnit (because of the cxx11 business in the STL headers that started in GCC 5.y)  and 2. If you're on a GCC 5.x based system, you'll need to build your own CppUnit if you want to use Clang (because of current inconsistencies in libstdc++ and libc++). I've already gotten used to having a cppunit module tied to the compiler because of the first exception, so it's not that big of deal. But comments welcome @roystgnr if you see a better way of handling that.
The second part of the PR introduces CppUnit based testing for the thermo interfaces in Cantera and Antioch. Currently only …
=> Add CppUnit Optional Testing Dependency, Update Thermo Interface Tests to Use CppUnit

README.md
We point to the libMesh page, which does describe the methods, but libMesh supports building more than one at a time while GRINS currently does not.
=> Clarify use of METHOD at configure time.

src/Makefile.am, src/common/include/grins/factory_with_getpot.h, src/common/include/grins/factory_with_getpot_physics_name.h, src/physics/include/grins/physics_factory_base.h, src/physics/src/physics_factory_base.C
Add a couple of low-level abstract factories so that we can reuse things like `set_getpot` across many different factories.
=> Factory Restructure

src/Makefile.am, src/variables/include/grins/variables_factory.h, src/variables/include/grins/variables_factory_base.h, src/variables/include/grins/variables_factory_with_physics_name.h, src/variables/src/variables_factory.C, src/variables/src/variables_factory_base.C, src/variables/src/variables_factory_with_physics_name.C, test/unit/variables.C
This PR adds factories for building `VariableBase` objects. We don't use these in the `Physics` as that's not the intended use case. Instead, we will use these to extract variable names during the boundary condition construction (downstream of this PR). This included CppUnit-based testing of several of the factories and testing of the use of `init_vars` in the intended use case.
=> Variable Factories

test/input_files/axisym_reacting_low_mach_antioch_cea_constant_regression.in, test/input_files/backward_facing_step.in, test/input_files/coupled_stokes_ns.in, test/input_files/locally_refine.in, test/input_files/reacting_low_mach_antioch_cea_constant_prandtl_regression.in, test/input_files/reacting_low_mach_antioch_cea_constant_regression.in, test/input_files/reacting_low_mach_antioch_kinetics_theory_regression.in, test/input_files/reacting_low_mach_antioch_statmech_blottner_eucken_lewis_arrhenius_catalytic_wall_regression.in, test/input_files/reacting_low_mach_antioch_statmech_blottner_eucken_lewis_constant_catalytic_wall_regression.in, test/input_files/reacting_low_mach_antioch_statmech_blottner_eucken_lewis_constant_gassolid_catalytic_wall_regression.in, test/input_files/reacting_low_mach_antioch_statmech_blottner_eucken_lewis_power_catalytic_wall_regression.in, test/input_files/reacting_low_mach_antioch_statmech_blottner_eucken_lewis_regression.in, test/input_files/reacting_low_mach_antioch_statmech_constant_prandtl_regression.in, test/input_files/reacting_low_mach_antioch_statmech_constant_regression.in, test/input_files/reacting_low_mach_cantera_regression.in, test/input_files/redistribute.in, test/input_files/stokes_invalid_pin_location_unit.in, test/input_files/vorticity_qoi.in
This doesn't remove `ParabolicProfile` from the code (that'll be later), this just removes its usage from the tests and puts `parsed_dirichlet` in its place.
=> Remove parabolic_profile from test input files

CHANGES, test/Makefile.am, test/input_files/parsed_qoi_scalar.in, test/regression/parsed_qoi_scalar.sh
Talked with @roystgnr about this briefly, and we both agreed this should be a tested capability. 
This case is almost a complete duplicate of the parsed_qoi.in test, but has been modified to ensure the parsed_qoi parsing appropriately handles scalars over the interior of the domain. This integral is analytically 5.0, and my machine is reporting,
<pre>
==========================================================
parsed_interior = 5.0000000000000648e+00
==========================================================
</pre>
e.g. 6.48e-14 error. Appears quite sane. However, any easy way to add this fact to the regression shell script? Right now it is just running, not testing this equality.
=> adding scalar parsed qoi test case

test/amr/convection_diffusion_unsteady_2d.sh, test/amr/input_files/convection_diffusion_unsteady_2d_amr.in
Sorry it took me so long to get around to this; GRINS "make check" wasn't working on libMesh --enable-parmesh builds.
=> Fix amr test

src/physics/include/grins/axisym_boussinesq_buoyancy.h, src/physics/include/grins/parsed_source_term.h, src/physics/src/axisym_boussinesq_buoyancy.C, src/physics/src/parsed_source_term.C
This should help prevent possible bugs if users choose stranger combinations of physics operators.
I was working on this preemptively to also fix any bugs triggered by https://github.com/libMesh/libmesh/pull/892 - however if there are any such, we don't hit them in the test suite.
=> Add missing init_context() overrides

src/physics/include/grins/physics_factory_reacting_flows.h, src/physics/src/physics_factory_reacting_flows.C
Had a name collision with the antioch-error-macro name that got
added in libantioch/antioch#185.
CI-server is supposed to be delievered 4/22. Hopefully it will be up and running shortly thereafter to catch this stuff. Sorry.
Going to merge right away since without this we can't compile with current Antioch master.
=> Uncollide helper function name with Antioch macro name

src/physics/include/grins/physics_naming.h, src/physics/src/physics_naming.C
`make check` failed all test due to segfaults with GCC 4.8.4. @pbauman traced issue back to static initialization fiasco in Physics Naming.
Encapsulated static `_suffix` variable in static function to fix.
All tests now passing.
=> fix for static initialization issues in physics_naming

src/physics/include/grins/parsed_velocity_source_adjoint_stab.h, src/physics/include/grins/velocity_penalty_adjoint_stab.h, src/physics/src/parsed_velocity_source_adjoint_stab.C, src/physics/src/velocity_penalty_adjoint_stab.C
The Viscosity is in the incompressible_navier_stokes_base class. Thanks to @nicholasmalaya for the concise test input file. @nicholasmalaya, this should fix the problems you were seeing.
=> Remove duplicate Viscosity objects

src/variables/include/grins/fe_variables_base.h, src/variables/src/fe_variables_base.C, test/unit/variables.C
Cherry-picked these off my bc-refactor branch. First commit is just a fixup (would've been nice to get a compiler warning).  Second is an extra test I'd gone ahead and plopped in. The last two commits add new features.
The first new feature is adding the notion of axisymmetry to the `FEVariableBase` objects. That is, downstream of this PR, we can decide (from parsing the input file) if we're working on axisymmetric problem or not. This is important for Neumann boundary conditions where we'll need the extra `r` factor in the Jacobian.
The second feature adds the tracking of the sign that will go in front of the Neumann boundary terms. For example, the heat equation and Maxwell's equation give differing signs on the natural boundary condition term.  However, it is preferable to be able to …
=> FEVariableBase: fixup, test, axisymmetry, Neumann BC sign

src/properties/src/cantera_mixture.C
So call the correct constructor since the default constructor
does not exist. Fix for compilation problem with Cantera introduced
in #391.
This gets GRINS compiling again for me with Cantera enabled (and make check still passes). Will merge right away.
=> CanteraMixture is now a ParameterUser subclass

src/physics/include/grins/elastic_cable_base.h, src/physics/src/solid_mechanics_abstract.C, src/variables/include/grins/fe_variables_base.h
API for setting Neumann BC sign introduced in #386 was stupid. This one is better. Also set up the correct sign for `SolidMechanics` `Physics`.  This does not effect code in master, but rather downstream in the BC refactoring, where it has been successfully tested.
=> Neumann BC sign: Redo FEVariableBase setter/SolidMechanics Sign Convention

doxygen/grins.dox.in
Set `TEMPLATE_RELATIONS = YES` and `INLINE_INHERITED_MEMB = NO`. The former is what I originally expected when using Doxygen with CRTP-type base classes. The latter I've really come to prefer. It significantly declutters looking for methods in the current class while still easily makes available base class methods.
=> Doxygen Option Changes

src/bc_handling/include/grins/bc_handling_base.h, src/bc_handling/src/bc_handling_base.C, src/bc_handling/src/heat_transfer_bc_handling.C, src/bc_handling/src/reacting_low_mach_navier_stokes_bc_handling.C, src/boundary_conditions/include/grins/catalytic_wall_base.h, src/boundary_conditions/src/catalytic_wall_base.C, src/boundary_conditions/src/gas_recombination_catalytic_wall.C, src/boundary_conditions/src/gas_solid_catalytic_wall.C, src/physics/include/grins/physics.h, src/physics/src/heat_transfer.C, src/physics/src/inc_navier_stokes.C, src/physics/src/physics.C, src/physics/src/reacting_low_mach_navier_stokes.C, src/variables/include/grins/fe_variables_base.h, src/variables/src/fe_variables_base.C, test/input_files/axi_poiseuille_flow_input.in, test/input_files/axi_thermally_driven_flow.in
This centralizes the notion of axisymmetry to the Physics. Originally, doing the BC refactoring, I was thinking the Variables would hold this, but I changed my mind and I think it makes more sense to keep this in the `Physics`. It still doesn't feel quite right, but I don't have a better solution at this point. 
Following this PR, the user will now be *required* to set `Physics/is_axisymmetric = true` if using the `axisymmetry` boundary condition. I asked @nicholasmalaya offline if he ran any axisymmetric cases and he said no, but I also think this extra safety is worth the backward-compatibility breakage.
I will also note that the somewhat incongruous usage of `Physics::is_axisymmetric()` in the catalytic wall boundary conditions will go away in the BC refactoring. The new API for …
=> Physics/Axisymmetry Consistency

src/physics/src/physics_factory_heat_transfer.C
This didn't really come out until the boundary condition refactoring.
=> Fix copy-paste error in HeatTransferPhysicsFactory

src/physics/src/convection_diffusion.C, src/variables/include/grins/fe_variables_base.h, src/variables/include/grins/generic_fe_type_variable.h, src/variables/include/grins/species_mass_fracs_fe_variables.h, src/variables/include/grins/variable_warehouse.h, test/unit/variables.C
Added two more accessors needed. Also updated `GenericFETypeVariable` to make `section_name()` public so the `Physics` can query it when registering. Finally, now have `ConvectionDiffusion` registering it's variable with the `VariableWarehouse`.
=> More FEVariableBase Updates

src/boundary_conditions/include/grins/parsed_function_traits.h, src/boundary_conditions/src/parsed_function_dirichlet_bc_factory.C, src/boundary_conditions/src/parsed_function_dirichlet_old_style_bc_factory.C
This compiles on gcc 6.1 and passes all the non-Antioch-based tests for me.  I'll try to get a new Antioch built to work around #410 so I can check those too shortly, but I think if we still pass "make check" on your system then we ought to be safe to merge.
=> Fix metaprogramming

src/Makefile.am, src/qoi/include/grins/rayfire_mesh.h, src/qoi/src/rayfire_mesh.C, test/Makefile.am, test/unit/input_files/mesh_quad4_5elem_1D.in, test/unit/input_files/mesh_quad4_9elem_2D.in, test/unit/input_files/mesh_quad9_5elem_1D.in, test/unit/input_files/mesh_quad9_9elem_2D.in, test/unit/rayfire_test.C
Adds the RayfireMesh class to QoI. This class creates a 1D mesh representing a straight path across a mesh. The intention is to use this to integrate functions along the rayfire.
Currently, only 2D meshes are supported. The CPPUnit test suite uses QUAD4 and QUAD9 element types, though any element type where build_side() returns an EDGE should (in theory) work.
More element types will be tested and supported as need arises.
=> RayfireMesh class

src/physics/include/grins/multiphysics_sys.h, src/physics/include/grins/physics.h, src/physics/src/multiphysics_sys.C
We override `FEMSystem::assembly()` and first do a `preassembly()` pass over each Physics. I have at least two use cases for this.
The one thing that concerns me though is that `System::update()` is called in `FEMSystem::assembly()` and one my of use cases will need to use the solution (to accumulate solution values along the (1D) mesh). This means that we'll endup calling `System::update()` twice in that case.
One solution could be we add an optional fourth argument to `FEMSystem::assembly()` - `bool do_solution_localization = true`. This will be compatible with internal library usage and give the hook for us to do the `update()` first and avoid the redundancy, but will obviously break API compatibility for anyone overriding `FEMSystem::assembly()`. Thoughts @roystgnr? (Obviously, this …
=> Add preassembly() hook for Physics

test/unit/rayfire_test.C
Otherwise when we build with a --enable-parmesh libMesh, this test
doesn't know what a serial mesh is.
=> Include serial_mesh.h in new rayfire test

src/qoi/include/grins/rayfire_mesh.h, src/qoi/src/rayfire_mesh.C, test/Makefile.am, test/unit/input_files/mesh_quad4_100elem_2D.in, test/unit/input_files/mesh_quad9_100elem_2D.in, test/unit/rayfireAMR_test.C, test/unit/rayfire_test.C
This PR adds AMR support to the RayfireMesh class (added in #418) and associated CPPUnit tests.
Refinement of the Rayfire mesh is done through the `RayfireMesh::reinit()` function, which must be called after each refinement of the main mesh. Right now, this must be done manually. However, in the near future, we will hook into MultiphysicsSystem to call `reinit()` on RayfireMesh objects in an upcoming QoI class.
The API change in the first commit was necessary to allow `RayfireMesh::reinit()` to have an empty parameter list (as will be required when the aforementioned hooks are added). Without a MeshBase object like in the `RayfireMesh::init(MeshBase&)` function, there was no was to get an `Elem*` from the elem IDs stored in the `RayfireMesh::_elem_map`. By storing `Elem*` instead of just …
=> RayfireMesh AMR

test/input_files/heat_eqn_unsteady_2d_restart_pt1.in, test/input_files/heat_eqn_unsteady_2d_restart_pt2.in
This isn't a GRINS bug, it's an exposure of a libMesh bug, but
unfortunately it's not a libMesh bug I have time to fix right now.
=> Require Mesh=serial for new restart test

src/qoi/src/rayfire_mesh.C
Not the subclass. In particular, this subclass is being removed
from post 1.0 libMesh, so this actually doesn't even compile.
=> Use header for PointLocatorBase

src/qoi/include/grins/rayfire_mesh.h, src/qoi/src/rayfire_mesh.C, test/unit/input_files/mixed_quad_tri.in, test/unit/rayfireAMR_test.C
Adds coarsening functionality to RayfireMesh, and a CPPUnit test for it.
Coarsening of the rayfire is done through storing the parent of refined rayfire elements. If that same element is later coarsened, we simply inactivate the children and activate the parent. The `RefinementState` is checked  in `map_to_rayfire_elem()` to ensure that only active rayfire elements get returned.
Note that the initial rayfire performed by `RayfireMesh::init()` must be done on the coarsest mesh before any refinements are done. Similar to how libMesh operates, we cannot coarsen the rayfire mesh beyond its initial version. Thus, a check was added to `RayfireMesh::init()` in 5370c06 to ensure that all elements along the rayfire are level 0.
Hooks to call `RayfireMesh::reinit()` post-refinement/coarsening will …
=> Rayfire coarsening

src/strategies/src/adaptive_time_stepping_options.C
libMesh uses a negative value here to signal "base my tolerance on the
time discretization error from the first successful time step", and we
should pass that along to enable that feature.
=> Enable AdaptiveTimeSolver with negative tolerance

test/common/system_helper.h
For unit tests that may be using "raw" MultiphysicsSystem (i.e. outside
of the Simulation class), this is one of the necessary steps. In
particular, this function caches a pointer to the GetPot object
that will be subsequently passed to things like the boundary condition
factories. So, let's make sure and call it when the developer is
using this testing helper function.
=> Call MultiphysicSystem::read_input_options() in testing helper

src/physics/include/grins/multiphysics_sys.h, src/physics/include/grins/physics.h, src/physics/src/multiphysics_sys.C
Some Physics may, internally, need to reinit things after AMR/C. This
provides the hook for them to be able to do so. Physics::reinit()
is called through MultiphysicsSystem::reinit() (and override of
FEMSystem reinit).
=> Provide Physics::reinit() Hooks

src/qoi/src/rayfire_mesh.C
This fixes warnings from GCC6.1 pointed out by @pbauman in #441.
For some context, on coarsening, we know the coarsened rayfire elem has to travel across the entire `parent_elem`. But since we have already calculated the intersection points for all the child elems, we can coarsen by just finding the node closest to the origin and farthest from it. So we iterate over all the child elems of our parent, and keep track of the start and end nodes, which later become the 2 nodes of the coarsened EDGE2 rayfire elem
=> RayfireMesh GCC warnings fix

src/qoi/include/grins/rayfire_mesh.h, src/qoi/src/rayfire_mesh.C, test/unit/rayfireAMR_test.C
These commits address memory leak complaints from Valgrind.
Fixes include removing unnecessary pointers in the `RayfireMesh` class and fixing an `invalid read` in the `rayfireAMR_test`. Neither of these affected the operation of the `RayfireMesh`, just the performance.
=> Rayfire memleak fix

src/qoi/include/grins/rayfire_mesh.h, src/qoi/src/rayfire_mesh.C, test/unit/rayfire_test.C
The `libMesh::PointLocatorBase` is used to find the elem of the mesh that contains the `origin` point of the rayfire.
However, the `PLB` returns the first elem it finds that contains the given `origin` point. When the origin is on an elem boundary, then multiple elems contain that point. Since PLB only returns the first elem it finds, it may not be the correct `start_elem` for the rayfire.
An additional check is added to find the correct starting elem. We walk a short distance along the rayfire, and check if we are still within the elem returned from the `PLB`. If not, then we do the same check with all neighbors of that elem to determine if any of them are along the rayfire. Since the origin must be on a mesh boundary, only the elem from the `PLB` and its neighbors would be valid …
=> Rayfire start_elem fix

test/regression/suspended_cable_test.sh
Cholesky sub_pc is not robust in parallel as the PC dies due
to indefiniteness using pc bjacobi. So, be gross and just use
GMRES with LU. This runs on 1-16 processors for me.
Fixes #447 and I think replaces #452. @roystgnr please confirm and sorry I didn't do this sooner.
=> Update suspended_cable_test options

src/Makefile.am, src/qoi/include/grins/integrated_function.h, src/qoi/include/grins/qoi_names.h, src/qoi/include/grins/rayfire_mesh.h, src/qoi/src/integrated_function.C, src/qoi/src/qoi_factory.C, src/qoi/src/rayfire_mesh.C, test/Makefile.am, test/common/regression_helper.h, test/unit/input_files/integrated_function_qoi_quad9.in, test/unit/input_files/integrated_function_quad9.in, test/unit/integrated_function_test.C
The `IntegratedFunction` class builds upon `RayfireMesh` to evaluate a given function along a 1D rayfire. Integration is done with Gauss Quadrature (`QGauss`).
The template parameter can be `FunctionBase` or `FEMFunctionBase`, depending on whether or not the `context` is needed to evaluate the function. An object of the templated type is then passed in to the constructor, and will be used to evaluate the function at the given quadrature points along the rayfire.
`IntegratedFunction` was then added to the `QoIFactory`, which allows us to run everything directly from an input file. User adds a `[QoI]` section with `integrated_function`, and must specify:
1. Rayfire origin coordinates (currently restricted to 2D)
2. Rayfire polar angle, theta
3. Function to be evaluated
4. Quadrature order …
=> Integrated Function QoI

src/Makefile.am, src/qoi/include/grins/qoi_base.h, src/qoi/include/grins/qoi_options.h, src/qoi/include/grins/qoi_output.h, src/qoi/src/qoi_base.C, src/qoi/src/qoi_output.C, src/solver/include/grins/grins_solver.h, src/solver/include/grins/simulation.h, src/solver/include/grins/solver_context.h, src/solver/src/grins_solver.C, src/solver/src/simulation.C, src/solver/src/steady_mesh_adaptive_solver.C, src/solver/src/unsteady_mesh_adaptive_solver.C, src/utilities/include/grins/output_parsing.h, test/input_files/3d_low_mach_jacobians_xy.in, test/input_files/3d_low_mach_jacobians_xz.in, test/input_files/3d_low_mach_jacobians_yz.in, test/input_files/extra_quadrature_order_laplace_arefee_amr_regression.in, test/input_files/low_mach_cavity_benchmark_regression_input.in, test/input_files/parsed_qoi.in, test/input_files/poisson_weighted_flux_regression.in, test/input_files/vorticity_qoi.in, test/unit/input_files/integrated_function_qoi_quad9.in
Long overdue, this PR adds the capability to output the QoI(s) to a text file as well as the terminal. The `QoIOutput` class handles parsing the options and deciding what modes to output - the actual QoI printing is still delegated to the QoI.
This will be used in refactoring the regression tests so that, for those tests with a QoI, we can just read in the QoI text files output from the grins run and compare to the gold values. Thus, right now, only the `print_qoi` option is actually tested in the test suite, but I've manually verified the file output in the `sa_airfoil` example.
Implicit in here is starting down the resectioning of output options in the input; hence the new `OutputParsing` class. Right now only the `[Output/QoI]` parts are there, but we might as well discuss this now so …
=> Update QoI Output and Corresponding Options

src/solver/src/grins_unsteady_solver.C
Looks like some header clean up upstream in libMesh.
Fixes #460.
=> Fix for missing header

examples/cavity_benchmark/cavity.C, examples/elastic_sheet/stretching_sheet.C, src/physics/include/grins/multiphysics_sys.h, src/physics/include/grins/physics.h, src/solver/include/grins/grins_solver.h, src/solver/include/grins/simulation.h, src/solver/src/grins.C, test/exact_soln/vorticity_qoi.C, test/regression/3d_low_mach_jacobians.C, test/regression/elastic_sheet_regression.C, test/regression/test_turbulent_channel.C, test/unit/builder_helper.C, test/unit/default_bc_builder.C, test/unit/hitran_test.C, test/unit/integrated_function_test.C, test/unit/mesh_builder.C, test/unit/rayfireAMR_test.C, test/unit/rayfire_test.C, test/unit/spectroscopic_absorption_test.C, test/unit/string_utils.C, test/unit/unit_driver.C, test/unit/variables.C
GRVY and CPPUnit use auto_ptr, and probably will for the foreseeable future.  But with the thousands of lines of "auto_ptr!  I saw an auto_ptr!  Did you know that's deprecated!?" disabled, I can actually read GCC warnings about our *own* code again.
=> Ignore third party library code in compiler warnings

src/physics/src/solid_mechanics_abstract.C
This fixes several test failures in dbg mode for me.
=> Don't set time_evolving() on nonexistant vars

src/physics/src/variable_pinning.C
My philosophy in this case was "continue running with pinning
disabled, because it would inconvenience users to just scream and
die", but my actual implementation was "pass a uninitialized variable
to libMesh and see what happens".  This fixes that.
=> Fix for VariablePinning without a variable to pin

examples/master_example_inputfile.in, src/solver/src/grins.C, test/exact_soln/generic_exact_solution_testing_app.C, test/exact_soln/poisson_periodic_2d_x.sh, test/input_files/poisson_periodic_2d_x.in, test/regression/3d_low_mach_jacobians.C, test/regression/elastic_sheet_regression.C, test/regression/generic_solution_regression.C, test/regression/grins_flow_regression.C, test/regression/low_mach_cavity_benchmark_regression.C, test/regression/regression_testing_app.C, test/regression/test_turbulent_channel.C
Allow users to override input file arguments on the command line.
I'm making this the default behavior for bin/grins, which I think is safe because it still would need to be done explicitly by users of libgrins.so, so we don't have to worry that any of our input-file options will suddenly cause namespace collisions with users' apps' command-line options.
=> Command line overrides

test/unit/spectroscopic_absorption_test.C
These tests require Antioch to calculate the QoI, so if GRINS was not configured with Antioch, these tests need to be skipped.
=> Skip SpectrscopicAbsorption test if not configured with Antioch

src/qoi/include/grins/rayfire_mesh.h, src/qoi/src/rayfire_mesh.C, test/unit/rayfireAMR_test.C
Recent work uncovered 2 bugs in the RayfireMesh class with non-square QUAD elements.
The first fix is for the case where the rayfire travels the boundary between 2 elements, one of which is to be refined. When updating the rayfire to reflect the refinement, it was possible for `RayfireMesh::refine()` to incorrectly identify elements along the rayfire due to the rayfire being along an element boundary. This caused the rayfire to wander into other elements, creating a hole in the rayfire that ultimately led to null pointer exceptions. This is fixed by adding a flag to certain private class functions to enforce when elements must have the same parent, as is the case when the rayfire is refined.
The second issue arises when the rayfire passes very close to vertices or element boundaries …
=> RayfireMesh fixes to handle special cases

src/solver/src/simulation.C
Follows [libMesh PR](https://github.com/libMesh/libmesh/pull/1233) to add an input option to disable coarsen/refine calls within `libMesh::EquationSystems::reinit`. Correct refinement flags are required for proper `RayfireMesh::reinit`. New option is `Strategies/MeshAdaptivity/disable_two_step_refinement`.
Tested with SpectroscopicAbsorption AMR run.
Do not merge until libMesh PR goes through.
=> new input option for Simulation to skip refinement calls in libMesh::EuqationSystems::reinit

src/physics/src/multiphysics_sys.C, src/qoi/include/grins/composite_qoi.h, src/qoi/include/grins/integrated_function.h, src/qoi/include/grins/qoi_base.h, src/qoi/src/composite_qoi.C, src/qoi/src/integrated_function.C, test/unit/input_files/integrated_function_quad9.in, test/unit/integrated_function_test.C
Hooks into `MultiphysicsSystem::reinit()` to also call `reinit()` on an attached `CompositeQoI`.
Included CPPUNIT tests fails without this, as the rayfire would not get refined along with the main mesh since `rayfire->reinit()` is not explicitly called in the test.
Also tests `libMesh::EquationSystems::reinit` flag from #478, without which this test will also fail because `es->reinit()` will clear the refinement flags on the main mesh and the rayfire will not get refined.
=> QoI reinit hooks in MultiphysicsSystem

src/physics/include/grins/reacting_low_mach_navier_stokes.h, src/physics/src/reacting_low_mach_navier_stokes.C
This uses a more inefficient way of computing these, but since we basically only want to do this for postprocessing/debugging/sanity-checking anyway, I'm not going to sweat the inefficiency of it at this point. I just wanted to capture this as it was/is part of debugging new thermo/transport models in reacting Low Mach.
=> Output Thermal Conductivity and Diffusion Coefficients

examples/transient_amr/convection_diffusion_unsteady_2d_amr.in
This breakage snuck in while I was refactoring `Variable` parsing. We really need to get example checking into CIVET.
Will merge this obvious fix once CIVET runs.
=> Fix broken example input file

src/Makefile.am, src/physics/src/averaged_turbine_base.C, src/physics/src/axisym_boussinesq_buoyancy.C, src/physics/src/axisym_heat_transfer.C, src/physics/src/boussinesq_buoyancy_base.C, src/physics/src/convection_diffusion.C, src/physics/src/heat_conduction.C, src/physics/src/heat_transfer_base.C, src/physics/src/heat_transfer_stab_helper.C, src/physics/src/inc_navier_stokes_base.C, src/physics/src/inc_navier_stokes_stab_helper.C, src/physics/src/low_mach_navier_stokes_base.C, src/physics/src/reacting_low_mach_navier_stokes_abstract.C, src/physics/src/scalar_ode.C, src/physics/src/solid_mechanics_abstract.C, src/physics/src/spalart_allmaras.C, src/physics/src/spalart_allmaras_helper.C, src/physics/src/spalart_allmaras_stab_helper.C, src/properties/src/spalart_allmaras_viscosity.C, src/qoi/include/grins/average_nusselt_number.h, src/qoi/include/grins/vorticity.h, src/qoi/src/average_nusselt_number.C, src/qoi/src/vorticity.C, src/variables/include/grins/variables_parsing.h, src/variables/src/variables_parsing.C
Two main sets of changes, the first set being required for the second.
The first set of changes is to rework the guts of how we call `VariableParsing` to get the variable name. It was more or less hardcoded to `Physics` before, but we'll also want to be able to parse variable information from other sections, so I generalized it.
The second is to update the QoIs that used variable indices to now use `FEVariablesBase` subclasses, similar to how we use them in `Physics`. This way, we have consistency in the parsing, in particular if the user wants to change how the variable section names are referenced in the input file.
These changes are leading up to refactoring QoI construction and a new QoIFactory (forthcoming).
=> Update VariableParsing Interface, Have QoIs Use FEVariablesBase Objects

README.md, src/physics/include/grins/antioch_instantiation_macro.h, src/physics/include/grins/reacting_low_mach_navier_stokes_macro.h, src/physics/src/physics_factory_reacting_flows.C, src/properties/include/grins/antioch_evaluator.h, src/properties/include/grins/antioch_kinetics.h, src/properties/include/grins/antioch_mixture.h, src/properties/include/grins/antioch_mixture_averaged_transport_mixture.h, src/properties/src/antioch_constant_transport_instantiate.C, src/properties/src/antioch_evaluator.C, src/properties/src/antioch_evaluator_instantiate.C, src/properties/src/antioch_mixture.C, test/interface/air_5sp.C
This adds in support for using `Antioch::IdealGasMicroThermo`, with NASA9, for reacting Low Mach physics kernels. Instead of trying to compute vibrational and electronic energies directly, this uses the NASA9 curve fits to get the total cv, etc., and then subtracts off `cv_trans` and `cv_rot` to get `cv_vib`, which is needed for some transport models.
I've done a little bit of testing in examples and seems to work OK, but I haven't been able to encapsulate as a regression test yet. So we can wait to merge until that time.
Future PRs will add NASA7 versions of this (which will require some tweaks to input parsing).
This should not be merged before libantioch/antioch#240 as this PR depends on that.
Actually, we shouldn't merge this until the README is updated with the commit on the Antioch …
=> Add Instantiations for Antioch::IdealGasMicroThermo/NASA9

src/apps/cantera_kinetic_rates.C, src/physics/include/grins/reacting_low_mach_navier_stokes_abstract.h, src/properties/src/antioch_kinetics.C
A little tidying up of warnings. If I turn of Cantera, this produces no warnings for me and, with a little build system work, we'll be able to start turning on `-Werror` on `femputer` builds.
I'll merge this very soon because I want to use this to test new `femputer` recipes I added for merges-to-master.
=> Cleanup Warnings

README.md, src/physics/include/grins/multiphysics_sys.h, src/physics/src/multiphysics_sys.C
Based on FEMSystem::assembly() API update in libMesh/libmesh#1342.
This will require bumping the minimum libMesh has to libMesh/libmesh@7f436d7. I'll let `femputer` run and then push an update to this PR with an updated README after I've updated the minimum grins-libmesh build on `femputer` to the new hash.
=> Update MultiphysicsSystem::assembly() API

README.md
I've updated the minimum libMesh on `femputer`, and in the GRINS README, to libMesh/libmesh@8be0a4e, corresponding to fixes by @roystgnr in libMesh/libmesh#1352. Thus, all tests should pass now.
=> Update minimum libMesh in README

src/qoi/include/grins/integrated_function.h, src/qoi/include/grins/qoi_factory.h, src/qoi/include/grins/rayfire_mesh.h, src/qoi/include/grins/spectroscopic_absorption.h, src/qoi/src/integrated_function.C, src/qoi/src/qoi_factory.C, src/qoi/src/rayfire_mesh.C, src/qoi/src/spectroscopic_absorption.C, test/unit/integrated_function_test.C
This PR fixes a memory leak. The internal `_mesh` in `RayfireMesh` was not getting properly destroyed because there seemed to be 3 copies of the `IntegratedFunction` class floating around, so the destructor wasn't ever called. I wasn't able to find the root cause, but this PR fixes the issue and is probably better design-wise.
674f3ac changes the internal `_elem_id_map` to not store raw `Elem*` for rayfire elems.
91c362c new constructor that passes the GetPot object through to the `RayfireMesh` class to allow it to construct itself. This is not strictly necessary I guess; we can just pass a `RayfireMesh*` to the `IntegratedFunction` constructor, which would then take control of the object. But I added this so that the rayfire would not have to be created outside `IntegratedFunction` and …
=> Fix memory leak in SpectroscopicAbsorption QoI

src/boundary_conditions/include/grins/arrhenius_catalycity.h, src/boundary_conditions/include/grins/catalycity_base.h, src/boundary_conditions/include/grins/catalycity_factories.h, src/boundary_conditions/include/grins/catalytic_wall_base.h, src/boundary_conditions/include/grins/constant_catalycity.h, src/boundary_conditions/include/grins/neumann_bc_abstract.h, src/boundary_conditions/include/grins/power_law_catalycity.h, src/boundary_conditions/src/arrhenius_catalycity.C, src/boundary_conditions/src/catalycity_base.C, src/boundary_conditions/src/catalytic_wall_base.C, src/boundary_conditions/src/constant_catalycity.C, src/boundary_conditions/src/power_law_catalycity.C, src/physics/src/multiphysics_sys.C, test/input_files/reacting_low_mach_antioch_statmech_blottner_eucken_lewis_arrhenius_catalytic_wall_regression.in, test/input_files/reacting_low_mach_antioch_statmech_blottner_eucken_lewis_constant_catalytic_wall_regression.in, test/input_files/reacting_low_mach_antioch_statmech_blottner_eucken_lewis_constant_gassolid_catalytic_wall_regression.in, test/input_files/reacting_low_mach_antioch_statmech_blottner_eucken_lewis_power_catalytic_wall_regression.in
Makes `CatalycityBase` a subclass of `ParameterUser` to allow for adding catalycity parameters for sensitivity analysis.
Requires updating `MultiphysicsSystem::register_parameter()` to search the `NeumannBC`s for the params as well, and making `NeumannBCAbstract` a subclass of `ParameterUser` as well
=> Make CatalycityBase derived from ParameterUser

src/qoi/include/grins/rayfire_mesh.h, src/qoi/src/rayfire_mesh.C, test/unit/rayfireAMR_test.C, test/unit/rayfire_test.C
Had these floating around, figured I should do a PR before they get lost.
These commits remove deprecated libMesh function calls in `RayfireMesh` (and associated tests) and replace them with their preferred versions.
=> Removing deprecated libMesh calls

src/qoi/include/grins/rayfire_mesh.h, src/qoi/src/rayfire_mesh.C, test/unit/rayfireAMR_test.C
Issues arose when calling `RafireMesh::init()` on an already refined mesh from a restart file.
The first case was that `INACTIVE` elements were being added to the rayfire. `Elem::neighbor_ptr()` gives the neighbor that is on the same refinement level as the current elem, whether or not that neighbor is `ACTIVE`. Instead, we have to check that the neighbor is active, and if it isn't, we check it's children to try and find the next elem for the rayfire. We also add asserts to try and catch these inactive elements.
The second case is not easily reproduced because it relies on the numbering of elem sides and edges as well as the coordinate values. If a refined elem shares its bottom edge with an unrefined elem and the rayfire traverses along that edge, then the rayfire may wander into the …
=> RayfireMesh::init() fixes for restart

src/boundary_conditions/src/default_bc_builder.C, src/physics/src/averaged_fan_base.C, src/physics/src/averaged_turbine_base.C, src/physics/src/axisym_heat_transfer.C, src/physics/src/convection_diffusion.C, src/physics/src/heat_conduction.C, src/physics/src/heat_transfer_base.C, src/physics/src/inc_navier_stokes_base.C, src/physics/src/low_mach_navier_stokes_base.C, src/physics/src/multiphysics_sys.C, src/physics/src/reacting_low_mach_navier_stokes_abstract.C, src/physics/src/scalar_ode.C, src/physics/src/solid_mechanics_abstract.C, src/physics/src/spalart_allmaras.C, src/physics/src/velocity_drag_base.C, src/solver/src/mesh_adaptive_solver_base.C, test/exact_soln/stokes_poiseuille_flow.sh, test/unit/integrated_function_test.C, test/unit/rayfireAMR_test.C
This gets rid of everything that libmesh/libmesh#1452 catches at compile time, at least.
=> Eliminate deprecated code usage

src/qoi/include/grins/hitran.h, src/qoi/src/hitran.C, test/unit/hitran_test.C
Main fix is where `HITRAN::T_index()` returned an index that was too high. It should return the index corresponding to the next data value higher than the given `T` but it was actually giving 2 indices higher for most cases.
Should use `std::floor(...) + 1` in all cases. Added additional tests with answer values obtained from `MATLAB interp1()` for verification. I also upped the tolerance for all tests because the previously returned incorrect values differed in the 8th digit and would not fail if using `libMesh::TOLERANCE = 1e-6`
Also updated private function names to match conventions and better describe their functionality.
=> HITRAN bugfix

src/qoi/include/grins/absorption_coeff.h, src/qoi/include/grins/hitran.h, src/qoi/src/absorption_coeff.C, src/qoi/src/hitran.C, src/utilities/include/grins/physical_constants.h, test/Makefile.am, test/interface/absorption_coeff_testing.h, test/unit/spectroscopic_absorption_test.C
This is part 1/2 of closed PR #505
Adds derivatives for each component of `AbsorptionCoeff`. Note this will not support AMR yet, as it does not contain the total QoI derivative. This will be added in a future PR.
For testing purposes, we created a subclass of `AbsorptionCoeff` named `AbsorptionCoeffTesting`. This class `friend`s the `SpectroscopicAbsorptionTest` class to allow access to the `protected` class functions of `AbsorptionCoeff`. We compare a central finite difference approximation of each component to its analytical derivative with respect to temperature, (hydrostatic) pressure, and mass fraction of the species of interest.
=> AbsorptionCoeff component derivatives

.gitignore
After bootstrapping and configuring GRINS, I end up with a ton of untracked files. This commit ignores them all, but I'm surprised no one has been annoyed by this before and I therefore might be missing something...
=> Ignore generated files.

src/ic_handling/include/grins/ic_handling_base.h, src/physics/include/grins/physics.h, src/qoi/include/grins/absorption_coeff.h, src/qoi/include/grins/composite_qoi.h, src/qoi/include/grins/parsed_boundary_qoi.h, src/qoi/include/grins/parsed_interior_qoi.h, src/solver/include/grins/mesh_adaptive_solver_base.h
In a separate commit, I will simply update all the UniquePtr instances
in GRINS to std::unique_ptrs.
Refs libMesh/libmesh#1525.
=> Include libmesh header that provides the UniquePtr alias.

README.md
As pointed out by @jwpeterson, we didn't mention we supported
out-of-source builds even though 1. We do, and 2. You should do that.
=> Update build notes for VPATH builds

src/Makefile.am, src/qoi/include/grins/absorption_coeff.h, src/qoi/include/grins/fem_function_and_derivative_base.h, src/qoi/include/grins/integrated_function.h, src/qoi/include/grins/spectroscopic_absorption.h, src/qoi/src/absorption_coeff.C, src/qoi/src/integrated_function.C, src/qoi/src/qoi_factory.C, src/qoi/src/spectroscopic_absorption.C, test/unit/spectroscopic_absorption_test.C
This PR is part 2/2 of PR #505 
Here we plug into the AMR infrastructure. `FEMFunctionAndDerivativeBase` extends `FEMFunctionBase` to add a new function that supports calculating derivatives with respect to state variables.
`finalize_derivative()` was added to `libMesh` in libMesh/linMesh#1445 which we need to apply the chain rule to our QoI.
We include a CPPUnit test that checks a finite difference approximation of `element_qoi()` against the output of `element_qoi_derivative()`.
There will be 1 more PR that will add a test for `assemble_qoi()` and add support for calculating derivatives with respect to all species in the flow, not just the species of interest as we have here.
=> SpectroscopicAbsorption QoI element_qoi_derivative

CHANGES, README.md, src/qoi/include/grins/absorption_coeff.h, src/qoi/include/grins/composite_qoi.h, src/qoi/include/grins/integrated_function.h, src/qoi/include/grins/qoi_base.h, src/qoi/include/grins/spectroscopic_absorption.h, src/qoi/src/absorption_coeff.C, src/qoi/src/composite_qoi.C, src/qoi/src/integrated_function.C, src/qoi/src/qoi_base.C, src/qoi/src/spectroscopic_absorption.C, test/unit/input_files/spectroscopic_absorption_qoi_fine.in, test/unit/spectroscopic_absorption_test.C
Finally, at long last, we have commit 3/2 of PR #505
Here we implement the `finalize_derivative()` function in `QoIBase` and `CompositeQoI`. By default, these implementations do nothing. This commit requires libMesh daf2f70
We then add a non-empty definition of `finalize_derivative()` to SpectroscopicAbsorption to give the correct derivative of the exponential QoI.
AbsorptionCoeff is updated so that derivatives are calculated with respect to all species within the flow, not just the absorbing species of interest.
Lastly, we add a CPPUnit test to verify the total QoI `assemble_qoi_derivative()` computation by comparing with a finite difference approximation.
With this PR, the SpectroscopicAbsorption QoI should give correct results for AMR.
=> SpectroscopicAbsorption assemble QoI Derivatives

src/solver/include/grins/simulation.h, src/solver/src/simulation.C
It's been deprecated for at least one release. Will rebase once #524 is merged.
=> Remove Deprecated Simulation Constructor

src/Makefile.am, src/physics/src/multiphysics_sys.C, src/solver/include/grins/nonlinear_solver_options.h, src/solver/include/grins/solver.h, src/solver/src/nonlinear_solver_options.C, src/solver/src/solver.C, test/Makefile.am, test/unit/nonlinear_solver_options.C
OK, I think I'm starting to figure the right way to contain parsing options. Because I'm an idiot, I've been thinking about `GetPot` as a parser (which it is) rather than a poor-man's-database (which is how we're using it). So, `NonlinearSolverOptions` is basically a very lightweight wrapper around `GetPot` so that we hide the key for which we parse. Then we can dump this object in where ever we need it because it's super lightweight, but we contain the things that might change to one class.
`ErrorEstimatorOptions`, `MeshAdaptivityOptions`, etc. should be refactored in this fashion.
Subsequent PR will change the sectioning for these options. More subsequent PRs will make similar changes to add a `LinearSolverOptions`,  `DisplayOptions`, etc.
Will rebase once #525 is merged (which will be …
=> Add and Use NonlinearSolverOptions Container

CHANGES, src/Makefile.am, src/solver/include/grins/diff_solver_factory.h, src/solver/include/grins/diff_solver_factory_initializer.h, src/solver/include/grins/diff_solver_names.h, src/solver/include/grins/nonlinear_solver_options.h, src/solver/include/grins/solver.h, src/solver/include/grins/solver_names.h, src/solver/src/diff_solver_factory.C, src/solver/src/diff_solver_factory_initializer.C, src/solver/src/simulation_initializer.C, src/solver/src/solver.C, test/Makefile.am, test/exact_soln/convection_diffusion_unsteady_2d_petsc_diff.sh, test/input_files/hot_cylinder.in, test/regression/hot_cylinder_petsc_diff.sh, test/unit/nonlinear_solver_options.C
This PR adds the factory pattern for `libMesh::DiffSolver`. Type is now controlled through input, with default going to `libMesh::NewtonSolver`, but we now support and test `libMesh::PetscDiffSolver`.
=> DiffSolver Factory, Support libMesh::PetscDiffSolver

CHANGES, README.md, test/Makefile.am, test/amr/convection_diffusion_unsteady_2d.sh, test/amr/convection_diffusion_unsteady_2d_petsc_diff.sh
@roystgnr 
This is currently broken and I'm trying to figure out why. ReplicatedMesh, 1 processor.
Manifesting as deteriorated Newton convergence and mismatch of solution values at hanging nodes. Attached picture is comparison with the exact same testing using `libMesh::NewtonSolver` instead of `libMesh::PetscDiffSolver` after completion of the second time step (first timestep is uniform grid, no AMR, and solutions match). Also posting output from log below.
Will open libMesh PR with my changes so far to `libMesh::PetscDiffSolver` and other comments there. Note those changes will be needed to get this test to run as I have in the log below because `PetscDiffSolver::reinit()` is wrong.
Log for PetscDiffSolver during second time step solve. Notice the linear convergence.
<pre>
Assembling …
=> Add unsteady AMR test using PetscDiffSolver

test/regression/axi_thermally_driven_flow.sh
With these options, GRINS "make check" again passes for me on 1 through
32 processors.  With no options axi_thermally_driven_flow.sh was failing
for me on 16 processors, the first value I tried.
I'm not sure how this wasn't already tripping up femputer...
=> PETSC_OPTIONS for axi_thermally_driven_flow test

test/exact_soln/ns_poiseuille_flow.sh
This prevents the test from breaking in parallel with np > 1 for me
with https://github.com/libMesh/libmesh/pull/1621
=> Use a better preconditioner for Poiseuille test

src/qoi/include/grins/spectroscopic_absorption.h, src/qoi/src/spectroscopic_absorption.C, test/unit/spectroscopic_absorption_test.C
`I/I0` is actually the **transmission** not the absorption.
The absorption is `1 - I/I0` or `(I0-I)/I0`
Technically, this should be merged before #534
=> Update SpectroscopicAbsorption QoI to actually calculate absorption

src/solver/src/mesh_builder.C, src/solver/src/simulation.C, src/solver/src/steady_mesh_adaptive_solver.C, src/strategies/src/adjoint_error_estimator_factories.C, src/visualization/src/visualization.C, test/amr/generic_amr_testing_app.C, test/regression/low_mach_cavity_benchmark_regression.C, test/regression/test_turbulent_channel.C
I'm preparing to forward declare most of the enums in libmesh (instead of #including their headers). This will require some slight changes in dependent apps, but luckily they can be made ahead of time.
Refs libMesh/libmesh#1713.
=> Update includes for new enum structure.

src/physics/include/grins/elastic_cable_rayleigh_damping.h, src/physics/include/grins/elastic_membrane_rayleigh_damping.h, src/physics/src/elastic_cable_rayleigh_damping.C, src/physics/src/elastic_membrane_rayleigh_damping.C
Piggybacking on #544.
We haven't updated the RayleighDamping Physics classes to support
the second_order_var interface so this will produce the incorrect
thing if we're using a libMesh::FirstOrderUnsteadySolver so we'll
error out for now until we can update to support this interface. Not
entirely trivial just because we'll need to deal with two different
Jacobians.
=> Error out Rayleigh Damping if using 1st order time solver

examples/master_example_inputfile.in, examples/ozone_flame/ozone_cantera.in, src/properties/include/grins/cantera_mixture.h, src/properties/include/grins/materials_parsing.h, src/properties/src/cantera_mixture.C, src/properties/src/materials_parsing.C, test/input_files/air_4sp.xml, test/input_files/air_5sp_test.xml, test/input_files/cantera_chem_thermo.in, test/input_files/cantera_transport.in, test/input_files/gas_surface.in, test/input_files/ozone_flame_cantera_regression.in, test/input_files/reacting_low_mach_cantera_regression.in, test/unit/input_files/variables_2d.in, test/unit/input_files/variables_arbitrary_names.in, test/unit/input_files/variables_species_cantera.in, test/unit/variables.C
Part 1 of a monster branch on refactoring the input parsing for thermochemistry. First is Cantera because was easier to do. 
In short, we've added a new option `chemical_data` that will correspond to the file that contains thermo, transport, and kinetics all in one XML file (this is standard for Cantera). Previously the option lived outside the Cantera section was specifically labeled as kinetics. Secondly, we don't require explicitly (and redundantly) setting the species in the GRINS input file, we now parse the species list from the XML file, based on the gas_mixture specified by the user (since there can be more than 1 mixture in the XML file, which we test). So the new format for Cantera will look like, for example,
<pre>
[Materials]
[./OzoneGas]
[./GasMixture]
thermochemistry_library …
=> Thermochemsity Parsing Refactoring Part 1: Cantera

src/physics/include/grins/elastic_cable.h, src/physics/include/grins/elastic_membrane.h, src/physics/src/elastic_cable.C, src/physics/src/elastic_membrane.C
We're eventually going to want to call these from an ImmersedBoundary type Physics kernel so let's do it separately now. We'll probably want to move to a CRTP interface for SolidMechanicsAbstract to encode this API, but let's actually try and see if this is the right thing to do before enforcing that.
=> Modularize Displacement Gradient, Stress, and Elasticity Computation in Solids Physics

examples/Makefile.am, examples/spectroscopy/README, examples/spectroscopy/opt_spectroscopy.in, src/qoi/include/grins/absorption_coeff.h, src/qoi/include/grins/absorption_coeff_base.h, src/qoi/include/grins/integrated_function.h, src/qoi/include/grins/spectroscopic_absorption.h, src/qoi/src/absorption_coeff.C, src/qoi/src/qoi_factory.C, src/qoi/src/spectroscopic_absorption.C
This PR generates the same absorption vs. wavenumber plot as the `Spectroscopy` example (#534) but utilizes the `CompositeQoI` class to dramatically speed up this process.
The `Spectroscopy` example loops over _N_ wavenumbers in a given range and recalculates the QoI every time. This results in looping over the entire mesh _N_ times, which is painfully slow for larger meshes or when _N_ is large.
Now, the user can specify `QoI/SpectroscopicAbsorption/desired_wavenumber = 'nu_min nu_max nu_step'` and a separate QoI will be created for each of the _N_ wavenumbers and added to `CompositeQoI`. This means that we only have to loop over the elements **once** and on each element we will calculate the qoi contributions for all _N_ wavenumbers.
Test case: 100x100 QUAD9 element mesh with conditions …
=> Better way to generate absorption plot

src/Makefile.am
This got overlooked in #554 and broke distcheck. Thanks femputer!
=> Add missing header to build system

doxygen/grins.dox.in, src/qoi/include/grins/rayfire_mesh.h, src/qoi/src/rayfire_mesh.C, test/unit/rayfire_test.C
We reformulate the calculation of the intersection between the rayfire line and the edge of a 2D element. 
When the 2D element is `FIRST` order, all edges are linear so we can actually solve for the intersection point analytically (see `intersection_2D_first_order()`). When the element is `SECOND` order, the edges may be quadratic so we use a Newton iterative solver to find the intersection point (see `intersection_2D_second_order()`)
Two new rayfire tests are included: one is a non-square QUAD4 element that is translated away from the origin, and the other is a QUAD9 where the top edge is quadratic.
To make clear documentation, the `amsmath` package was included in the `doxygen` configuration to allow for the use of `bmatrix` in the comments.
=> New rayfire 2D solvers

src/qoi/src/rayfire_mesh.C, test/unit/rayfire_test_3d.C
Through testing on a large 27k element 3D mesh, we found that the 3D `SECOND` order rayfire intersection point solver did not adequately converge to pass a `libMesh::Elem::contains_point()` check.
This issue is solved by changing the convergence tolerance of the newton step vector l2 norm to `libMesh::TOLERANCE*side_elem->hmax()` based on the checks within `contains_point()` itself. 
However, should the mesh contain large elements of size O(1), we may get a tolerance that is too large. So, we added a floor to the tolerance of `libMesh::TOLERANCE` and use `std::min()` to choose the smaller of the two. This way, smaller elements can have a tighter tolerance to make sure they sufficiently converge, while large elements might not need such strict convergence.
A CPPUnit test was added based on …
=> Rayfire newton solver fix

examples/master_example_inputfile.in, src/solver/src/mesh_builder.C
Default behavior is unchanged, but these can be useful for example
to cut out unneeded work when constructing a GMG hierarchy.
=> Add in options to be used in input file for mesh refinement settings.

src/Makefile.am, src/qoi/include/grins/absorption_coeff.h, src/qoi/include/grins/collimated_gaussian_laser_intensity_profile.h, src/qoi/include/grins/constant_laser_intensity_profile.h, src/qoi/include/grins/laser_absorption.h, src/qoi/include/grins/laser_intensity_profile_base.h, src/qoi/include/grins/multi_qoi_base.h, src/qoi/include/grins/qoi_factory.h, src/qoi/include/grins/qoi_names.h, src/qoi/src/absorption_coeff.C, src/qoi/src/collimated_gaussian_laser_intensity_profile.C, src/qoi/src/constant_laser_intensity_profile.C, src/qoi/src/laser_absorption.C, src/qoi/src/laser_intensity_profile_base.C, src/qoi/src/multi_qoi_base.C, src/qoi/src/qoi_factory.C
Here we add a new QoI that can compute the total absorbed laser intensity across a two-dimensional "laser beam". We use Gauss quadrature to integrate the initial and final laser intensity profiles, and then take their ratio and subtract from 1 to get the absorption QoI value. To calculate the final intensity profile, we needed to do a transmission calculation at each quadrature point.
As such, we needed a QoI object similar to `CompositeQoI` that could store QoI objects internally but was itself derived from `QoIBase`. Hence, `MultiQoIBase` was created as an amalgamation of `QoIBase` and `CompositeQoI`. The `LaserAbsorption` class was then derived from this new class and stores `SpectroscopicTransmission` objects internally.
We also added new classes to evaluate the laser intensity at a …
=> LaserAbsorption QoI class

src/qoi/include/grins/laser_absorption.h, src/qoi/src/laser_absorption.C, src/qoi/src/qoi_factory.C, test/Makefile.am, test/interface/spectroscopic_test_base.h, test/unit/input_files/spectroscopic_base.in, test/unit/laser_absorption_test.C
We add support for using the `LaserAbsorption` QoI on 3D meshes, as an extension to #567. We also add CPPUnit tests on 2D and 3D meshes that use the same flow field as the `spectroscopic` tests, and hence should yield the same QoI values.
For 3D, we use a `QUAD9` elem to define the shape of the circular laser cross-section. We use vector algebra to define the nodes of the QUAD9 from the given 3 points and then attach a quadrature rule. The rest proceeds exactly as in the 2D scenario.
Note that AMR support is **not** included in this PR.
=> LaserAbsorption QoI 3D support and CPPUnit tests

src/qoi/include/grins/rayfire_mesh.h, src/qoi/src/rayfire_mesh.C, test/unit/rayfire_test_3d.C
This PR fixes a failure that was observed in a 3D `HEX27` mesh where the rayfire was unable to calculate an intersection point on certain elements. Inspection of these elements revealed that the `HEX8` version had non-linear faces, and so the `RayfireMesh::intersection_3D_first_order(...)` function would fail since it assumed faces were planes.
To address this issue, we drop the `FIRST` order 3D function and instead use the `SECOND` order newton solver function for all 3D elements. This will account for all nonlinearity (since it operates on the elem reference coordinates `xi` and `eta`).
A new CPPUnit test was added for a 3D `HEX27` that previously caused a failure. This fix was also tested on the larger `HEX27` mesh and no failure was found.
=> Rayfire 3D fix

src/boundary_conditions/include/grins/arrhenius_catalycity.h, src/boundary_conditions/include/grins/catalycity_base.h, src/boundary_conditions/include/grins/catalytic_wall_base.h, src/boundary_conditions/include/grins/constant_catalycity.h, src/boundary_conditions/include/grins/power_law_catalycity.h, src/boundary_conditions/src/arrhenius_catalycity.C, src/boundary_conditions/src/catalytic_wall_base.C, src/boundary_conditions/src/constant_catalycity.C, src/boundary_conditions/src/power_law_catalycity.C
I've probably created this code 3 times over the past year but I keep losing it among all my branches and such, so I was hoping we could merge this.
All this does is return the catalycity parameter values from `CatalycityBase` as a 'getter' complement to `set_params()`.
I use this right now as a debugging helper and outputter for a `QUESO` integration.
=> Add new getter function to CatalycityBase

test/regression/reacting_low_mach_antioch_kinetics_theory.sh
Switching PETSc has changed digits slightly. I can't reproduce the failures seen on femputer so far, but this will be needed regardless. Let's see if we see the failures on femputer now.
=> Loosen tolerance on one Antioch test

src/physics/include/grins/overlapping_fluid_solid_map.h, src/physics/src/overlapping_fluid_solid_map.C, test/unit/overlapping_fluid_solid_mesh.C
Updated the API to be more user friendly and avoid gross data types. Also now fixed the lack of parallel syncing which was ultimately an issue downstream for getting a `GhostingFunctor` to work correctly. This uses `libMesh::Parallel::push_parallel_vector_data`, which now uses the NBX (non-blocking consensus) algorithm. We'll see if the older libMesh used the same API before this was updated on the libMesh side. If not, then we'll bump the minimum libMesh version (which we're going to do for GMG anyway). ATM, we don't have any unit testing of the parallel_sync (see #575).
=> Refactor OverlappingFluidSolidMap

examples/Makefile.am
Files for the multigrid example were not being packed in a distribution
tarball.
=> Fix for distcheck

src/qoi/src/laser_absorption.C
get_node was deprecated and is now being removed in libMesh/libmesh#2104
so it's time to remove the deprecated function calls.
=> Use node_ptr vs get_node

src/physics/include/grins/multiphysics_sys.h, src/physics/include/grins/physics.h, src/physics/src/multiphysics_sys.C
Adds the `Physics::presolve()` API that is a cousin of `Physics::preassembly()`. While `Physics::preassembly()` will be called at each assembly call in each Newton iteration, `Physics::presolve()` is only called once before each nonlinear solve. We'll use this API with the immersed boundary stuff Coming Soon(TM) (for the semi-implicit version, while preassembly is used for the fully implicit version).
While I was in `MultiphysicsSystem`, I went ahead and did a sweep of C++11 isms in that file in that last commit in this PR. Net (-50) lines in that commit and (-20) in this PR so I'll take it.
=> Add Physics::presolve() API

src/Makefile.am, src/physics/include/grins/overlapping_fluid_solid_coupling_functor.h, src/physics/src/overlapping_fluid_solid_coupling_functor.C
Cherry-picked this off our working Immersed Boundary branch. This is the `GhostingFunctor` subclass that is the full coupling functor corresponding to `OverlappingFluidSolidMap`.
This could be made more generic to multicomponent variables, but not going down that road now.
=> Add OverlappingFluidSolidCouplingFunctor

src/physics/include/grins/overlapping_fluid_solid_map.h, src/physics/src/overlapping_fluid_solid_map.C
Builds on #583. Will rebase when that's merged.
This adds an optional flag to `OverlappingFluidSolidMap` construction to allow the user to specify if they want to use an old solution. If so, then we swap in `UnsteadySolver::old_local_nonlinear_solution` for `System::current_local_solution`, build the overlapping map, and then swap back. This will allow us to easily do a semi-implicit vs. fully-implicit treatment in the immersed boundary stuff.
=> Enable OverlappingFluidSolidMap to use old solution

examples/master_example_inputfile.in, src/boundary_conditions/include/grins/parsed_function_dirichlet_bc_factory.h, src/boundary_conditions/src/boundary_condition_factory_initializer.C, src/boundary_conditions/src/parsed_function_dirichlet_bc_factory.C
Before this PR, when the user had a multicomponent Variable and only set a subset of the Dirichlet values, the remainder were automatically set to zero (this is useful for example in reacting flow applications were we only want to set a handful of species mass fractions out of a set of 300+). However, there are cases were we don't want them to be zeroed (solid mechanics is where this is cropping up for me). So I've updated the `ParsedDirichletBCFactoryBase` to handle this and instantiated new BCFactories that support this. The option is `parsed_dirichlet_component` which is the new behavior and the previous behavior is kept at `parsed_dirichlet`. Similarly for `parsed_fem_dirichlet_component`. Open to suggestions if someone has a better name.
=> parsed_dirichlet_component Boundary Condition Option

configure.ac, examples/Makefile.am, examples/multigrid/README, examples/multigrid/run_thermo_coupled_flow.sh.in, examples/multigrid/thermo_coupled_flow.in
This PR expands the GMG multigrid coverage by adding a new thermally coupled flow example which uses the fixed up solver configuration settings that were part of the changes in libMesh/libmesh#2151; as such this PR requires the bumping of minimum libMesh version to that corresponding to the libMesh PR.
The content here provides a new example that is run twice with the idea of demonstrating broad categories of solver configuration capabilities. The first run uses recursive Schur complement decomposition to solve the coupled problem, while the second run uses a multiplicative fieldsplit variant with GMG to precondition the velocity subblock, and GMG on the thermal convective/diffusive subblock.
Please let me know if there's anything to be improved upon!
=> Add Thermally Coupled GMG Examples

src/boundary_conditions/src/default_bc_builder.C, src/constraints/src/constrained_points.C, src/qoi/src/qoi_output.C
I haven't been quite up to date with recent libMesh changes but upon using master and trying to build GRINS I ran into a few compilation and linker errors.
I noticed some refactoring in libMesh#2219 which seems like the likely culprit, although I didn't verify this explicitly. Just thought Id submit this PR to save anyone else the potential trouble I ran into.
=> Include missing parallel headers

src/physics/src/multiphysics_sys.C, src/solver/include/grins/mesh_builder.h, src/solver/include/grins/simulation.h, src/solver/include/grins/simulation_builder.h, src/utilities/include/grins/distance_function.h, src/visualization/include/grins/steady_visualization.h, src/visualization/include/grins/unsteady_visualization.h, src/visualization/include/grins/visualization.h, src/visualization/include/grins/visualization_factory.h
This should be backwards compatible for quite a ways, and fixes compilation for me with newer libMesh versions.
=> Libmesh compatibility updates

src/qoi/src/spectroscopic_absorption.C, src/qoi/src/spectroscopic_transmission.C, src/visualization/src/steady_visualization.C, src/visualization/src/unsteady_visualization.C, test/regression/test_turbulent_channel.C
Looks like we were previously getting this indirectly via time_solver.h
and subclasses, but the forward declarations in
https://github.com/libMesh/libmesh/pull/2647 mean we need to get things
ourselves now.
=> Include numeric_vector.h directly

src/physics/src/overlapping_fluid_solid_map.C
And in libMesh after 1.6, those two vectors are two different kinds of
smart ptr.
We'll rely on NumericVector::swap() here instead.  That means we need
the full header, too, not just a forward declaration.
This fixes compilation with the latest libMesh git head for me; hopefully it fixes #598 too.
=> Can't std::swap two different kinds of smart ptr

src/qoi/include/grins/absorption_coeff.h, src/qoi/include/grins/average_nusselt_number.h, src/qoi/include/grins/composite_qoi.h, src/qoi/include/grins/multi_qoi_base.h, src/qoi/include/grins/parsed_interior_qoi.h, src/qoi/include/grins/qoi_base.h, src/qoi/src/absorption_coeff.C, src/qoi/src/average_nusselt_number.C, src/qoi/src/composite_qoi.C, src/qoi/src/multi_qoi_base.C, src/qoi/src/parsed_interior_qoi.C, src/qoi/src/qoi_factory.C, src/qoi/src/vorticity.C, src/qoi/src/weighted_flux_qoi.C, src/solver/include/grins/simulation_builder.h, src/solver/src/simulation_builder.C, test/unit/integrated_function_test.C
This builds off of #605, will rebase on master once that's merged.
These were all picked up during my work on trying to get GRINS working with libMesh built with `--disable-deprecated`. I split off these commits in their own PR so the eventual PR getting `--disable-deprecated` working is more focused.
=> More cleaning

src/solver/src/mesh_builder.C
libMesh Elem::centroid was deprecated, since its name didn't match its
behavior.
=> Use vertex_average (what "centroid" used to give)

README.md, examples/elastic_sheet/displacement_continuation_solver.C, src/physics/src/multiphysics_sys.C, src/qoi/include/grins/composite_qoi.h, src/qoi/src/composite_qoi.C, src/solver/src/simulation.C, src/solver/src/steady_mesh_adaptive_solver.C, src/solver/src/unsteady_solver.C, test/interface/spectroscopic_test_base.h, test/regression/generic_solution_regression.C
This gets us building again with libMesh master.  Breaks us with old libMesh, though; I wish I had time to think of a smoother upgrade path on the deprecation of direct System::qoi access and the old init_qoi() virtual.
=> Libmesh updates

src/physics/include/grins/overlapping_fluid_solid_coupling_functor.h, src/physics/src/overlapping_fluid_solid_coupling_functor.C
This captures the changes made upstream in libMesh in the API that were made for performance reasons in libMesh/libmesh#3431.
=> Use GhostingFunctor::map_type rather than unordered_map
